#
# Makefile for Marvell's PXA168 processors line
#

obj-y				+= common.o clock.o devices.o irq.o time.o

# SoC support
obj-$(CONFIG_CPU_PXA168)	+= pxa168.o

# board support
obj-$(CONFIG_MACH_ZYLONITE2)	+= zylonite2.o
