
/**************************************************************************
 *
 * Copyright (c) 2008 Intel Corporation,
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sub license, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDERS, AUTHORS AND/OR ITS SUPPLIERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 **************************************************************************/

#ifndef _LNC_TOPAZ_H_
#define _LNC_TOPAZ_H_

#include "psb_drv.h"

int psb_power_up_topaz(struct drm_device *dev);
int psb_power_down_topaz(struct drm_device *dev);

/*
 * MACROS to insert values into fields within a word. The basename of the
 * field must have MASK_BASENAME and SHIFT_BASENAME constants.
 */
#define MM_WRITE32(base, offset, value)  \
do {				       \
	*((unsigned long *)((unsigned char *)(dev_priv->topaz_reg)	\
				+ base + offset)) = value;		\
} while (0)

#define MM_READ32(base, offset, pointer) \
do {                                   \
	*(pointer) = *((unsigned long *)((unsigned char *)(dev_priv->topaz_reg)\
						+ base + offset));	\
} while (0)

#define F_MASK(basename)  (MASK_##basename)
#define F_SHIFT(basename) (SHIFT_##basename)

#define F_ENCODE(val, basename)  \
	(((val) << (F_SHIFT(basename))) & (F_MASK(basename)))

/* MVEA macro */
#define MVEA_START 0x03000

#define MVEA_WRITE32(offset, value) MM_WRITE32(MVEA_START, offset, value)
#define MVEA_READ32(offset, pointer) MM_READ32(MVEA_START, offset, pointer);

#define F_MASK_MVEA(basename)  (MASK_MVEA_##basename)	/*     MVEA    */
#define F_SHIFT_MVEA(basename) (SHIFT_MVEA_##basename)	/*     MVEA    */
#define F_ENCODE_MVEA(val, basename)  \
	(((val)<<(F_SHIFT_MVEA(basename)))&(F_MASK_MVEA(basename)))

/* VLC macro */
#define TOPAZ_VLC_START 0x05000

/* TOPAZ macro */
#define TOPAZ_START 0x02000

#define TOPAZ_WRITE32(offset, value) MM_WRITE32(TOPAZ_START, offset, value)
#define TOPAZ_READ32(offset, pointer) MM_READ32(TOPAZ_START, offset, pointer)

#define F_MASK_TOPAZ(basename)  (MASK_TOPAZ_##basename)
#define F_SHIFT_TOPAZ(basename) (SHIFT_TOPAZ_##basename)
#define F_ENCODE_TOPAZ(val,basename) \
	(((val)<<(F_SHIFT_TOPAZ(basename)))&(F_MASK_TOPAZ(basename)))

/* MTX macro */
#define MTX_START 0x0

#define MTX_WRITE32(offset, value) MM_WRITE32(MTX_START, offset, value)
#define MTX_READ32(offset, pointer) MM_READ32(MTX_START, offset, pointer)

/* DMAC macro */
#define DMAC_START 0x0f000

#define DMAC_WRITE32(offset, value) MM_WRITE32(DMAC_START, offset, value)
#define DMAC_READ32(offset, pointer) MM_READ32(DMAC_START, offset, pointer)

#define F_MASK_DMAC(basename)  (MASK_DMAC_##basename)
#define F_SHIFT_DMAC(basename) (SHIFT_DMAC_##basename)
#define F_ENCODE_DMAC(val,basename)  \
	(((val)<<(F_SHIFT_DMAC(basename)))&(F_MASK_DMAC(basename)))


/* **************** mvea register define **************** */

#define MVEA_CR_IMG_MVEA_SRST       0x0000
#define MASK_MVEA_CR_IMG_MVEA_SPE_SOFT_RESET 0x00000001
#define SHIFT_MVEA_CR_IMG_MVEA_SPE_SOFT_RESET 0
#define REGNUM_MVEA_CR_IMG_MVEA_SPE_SOFT_RESET 0x0000

#define MASK_MVEA_CR_IMG_MVEA_IPE_SOFT_RESET 0x00000002
#define SHIFT_MVEA_CR_IMG_MVEA_IPE_SOFT_RESET 1
#define REGNUM_MVEA_CR_IMG_MVEA_IPE_SOFT_RESET 0x0000

#define MASK_MVEA_CR_IMG_MVEA_CMPRS_SOFT_RESET 0x00000004
#define SHIFT_MVEA_CR_IMG_MVEA_CMPRS_SOFT_RESET 2
#define REGNUM_MVEA_CR_IMG_MVEA_CMPRS_SOFT_RESET 0x0000

#define MASK_MVEA_CR_IMG_MVEA_JMCOMP_SOFT_RESET 0x00000008
#define SHIFT_MVEA_CR_IMG_MVEA_JMCOMP_SOFT_RESET 3
#define REGNUM_MVEA_CR_IMG_MVEA_JMCOMP_SOFT_RESET 0x0000

#define MASK_MVEA_CR_IMG_MVEA_CMC_SOFT_RESET 0x00000010
#define SHIFT_MVEA_CR_IMG_MVEA_CMC_SOFT_RESET 4
#define REGNUM_MVEA_CR_IMG_MVEA_CMC_SOFT_RESET 0x0000

#define MASK_MVEA_CR_IMG_MVEA_DCF_SOFT_RESET 0x00000020
#define SHIFT_MVEA_CR_IMG_MVEA_DCF_SOFT_RESET 5
#define REGNUM_MVEA_CR_IMG_MVEA_DCF_SOFT_RESET 0x0000

/* Register CR_IMG_MVEA_INTSTAT */
#define MVEA_CR_IMG_MVEA_INTSTAT    0x0004
#define MASK_MVEA_CR_IMG_MVEA_INTS_SPE_DONE 0x00000001
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_SPE_DONE 0
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_SPE_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_IPE_DONE 0x00000002
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_IPE_DONE 1
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_IPE_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_CMPRS_DONE 0x00000004
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_CMPRS_DONE 2
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_CMPRS_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_JMCOMP_DONE 0x00000008
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_JMCOMP_DONE 3
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_JMCOMP_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_EDMA_DONE 0x00000010
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_EDMA_DONE 4
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_EDMA_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_TDMA_DONE 0x00000020
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_TDMA_DONE 5
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_TDMA_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_DEB_DONE 0x00000040
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_DEB_DONE 6
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_DEB_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_VLC_DONE 0x00000080
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_VLC_DONE 7
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_VLC_DONE 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_SOFTWARE0 0x00000100
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_SOFTWARE0 8
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_SOFTWARE0 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_SOFTWARE1 0x00000200
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_SOFTWARE1 9
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_SOFTWARE1 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_DCF_EMPTY 0x00000400
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_DCF_EMPTY 10
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_DCF_EMPTY 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_COMBINED 0x40000000
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_COMBINED 30
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_COMBINED 0x0004

#define MASK_MVEA_CR_IMG_MVEA_INTS_MASTER 0x80000000
#define SHIFT_MVEA_CR_IMG_MVEA_INTS_MASTER 31
#define REGNUM_MVEA_CR_IMG_MVEA_INTS_MASTER 0x0004

/* Register CR_IMG_MVEA_INTENAB */
#define MVEA_CR_IMG_MVEA_INTENAB    0x0008
#define MASK_MVEA_CR_IMG_MVEA_INTEN_SPE_DONE 0x00000001
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_SPE_DONE 0
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_SPE_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_IPE_DONE 0x00000002
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_IPE_DONE 1
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_IPE_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_CMPRS_DONE 0x00000004
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_CMPRS_DONE 2
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_CMPRS_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_JMCOMP_DONE 0x00000008
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_JMCOMP_DONE 3
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_JMCOMP_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_EDMA_DONE 0x00000010
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_EDMA_DONE 4
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_EDMA_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_TDMA_DONE 0x00000020
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_TDMA_DONE 5
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_TDMA_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_DEB_DONE 0x00000040
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_DEB_DONE 6
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_DEB_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_VLC_DONE 0x00000080
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_VLC_DONE 7
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_VLC_DONE 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE0 0x00000100
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE0 8
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE0 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE1 0x00000200
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE1 9
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_SOFTWARE1 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_DCF_EMPTY 0x00000400
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_DCF_EMPTY 10
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_DCF_EMPTY 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_COMBINED 0x40000000
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_COMBINED 30
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_COMBINED 0x0008

#define MASK_MVEA_CR_IMG_MVEA_INTEN_MASTER 0x80000000
#define SHIFT_MVEA_CR_IMG_MVEA_INTEN_MASTER 31
#define REGNUM_MVEA_CR_IMG_MVEA_INTEN_MASTER 0x0008

/* Register CR_IMG_MVEA_INTCLEAR */
#define MVEA_CR_IMG_MVEA_INTCLEAR   0x000C
#define MASK_MVEA_CR_IMG_MVEA_INTCLR_SPE_DONE 0x00000001
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_SPE_DONE 0
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_SPE_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_IPE_DONE 0x00000002
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_IPE_DONE 1
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_IPE_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_CMPRS_DONE 0x00000004
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_CMPRS_DONE 2
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_CMPRS_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_JMCOMP_DONE 0x00000008
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_JMCOMP_DONE 3
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_JMCOMP_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_EDMA_DONE 0x00000010
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_EDMA_DONE 4
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_EDMA_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_TDMA_DONE 0x00000020
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_TDMA_DONE 5
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_TDMA_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_DEB_DONE 0x00000040
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_DEB_DONE 6
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_DEB_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_VLC_DONE 0x00000080
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_VLC_DONE 7
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_VLC_DONE 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE0 0x00000100
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE0 8
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE0 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE1 0x00000200
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE1 9
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_SOFTWARE1 0x000C

#define MASK_MVEA_CR_IMG_MVEA_INTCLR_DCF_EMPTY 0x00000400
#define SHIFT_MVEA_CR_IMG_MVEA_INTCLR_DCF_EMPTY 10
#define REGNUM_MVEA_CR_IMG_MVEA_INTCLR_DCF_EMPTY 0x000C

/* Register CR_IMG_MVEA_INT_COMB_SEL */
#define MVEA_CR_IMG_MVEA_INT_COMB_SEL 0x0010
#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_SPE_DONE 0x00000001
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_SPE_DONE 0
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_SPE_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_IPE_DONE 0x00000002
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_IPE_DONE 1
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_IPE_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_CMPRS_DONE 0x00000004
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_CMPRS_DONE 2
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_CMPRS_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_JMCOMP_DONE 0x00000008
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_JMCOMP_DONE 3
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_JMCOMP_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_EDMA_DONE 0x00000010
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_EDMA_DONE 4
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_EDMA_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_TDMA_DONE 0x00000020
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_TDMA_DONE 5
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_TDMA_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_DEB_DONE 0x00000040
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_DEB_DONE 6
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_DEB_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_VLC_DONE 0x00000080
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_VLC_DONE 7
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_VLC_DONE 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE0 0x00000100
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE0 8
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE0 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE1 0x00000200
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE1 9
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_SOFTWARE1 0x0010

#define MASK_MVEA_CR_IMG_MVEA_INTCSEL_DCF_EMPTY 0x00000400
#define SHIFT_MVEA_CR_IMG_MVEA_INTCSEL_DCF_EMPTY 10
#define REGNUM_MVEA_CR_IMG_MVEA_INTCSEL_DCF_EMPTY 0x0010

/* Register CR_MVEA_START */
#define MVEA_CR_MVEA_START          0x0014
#define MASK_MVEA_CR_MVEA_SPE_START 0x00000001
#define SHIFT_MVEA_CR_MVEA_SPE_START 0
#define REGNUM_MVEA_CR_MVEA_SPE_START 0x0014

#define MASK_MVEA_CR_MVEA_IPE_START 0x00000002
#define SHIFT_MVEA_CR_MVEA_IPE_START 1
#define REGNUM_MVEA_CR_MVEA_IPE_START 0x0014

#define MASK_MVEA_CR_MVEA_CMPRS_START 0x00000004
#define SHIFT_MVEA_CR_MVEA_CMPRS_START 2
#define REGNUM_MVEA_CR_MVEA_CMPRS_START 0x0014

#define MASK_MVEA_CR_MVEA_JMCOMP_START 0x00000008
#define SHIFT_MVEA_CR_MVEA_JMCOMP_START 3
#define REGNUM_MVEA_CR_MVEA_JMCOMP_START 0x0014

#define MASK_MVEA_CR_MVEA_DEB_START 0x00000040
#define SHIFT_MVEA_CR_MVEA_DEB_START 6
#define REGNUM_MVEA_CR_MVEA_DEB_START 0x0014

#define MASK_MVEA_CR_MVEA_VLC_START 0x00000080
#define SHIFT_MVEA_CR_MVEA_VLC_START 7
#define REGNUM_MVEA_CR_MVEA_VLC_START 0x0014

/* Register CR_MVEA_BUSY */
#define MVEA_CR_MVEA_BUSY           0x0018
#define MASK_MVEA_CR_MVEA_SPE_BUSY  0x00000001
#define SHIFT_MVEA_CR_MVEA_SPE_BUSY 0
#define REGNUM_MVEA_CR_MVEA_SPE_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_IPE_BUSY  0x00000002
#define SHIFT_MVEA_CR_MVEA_IPE_BUSY 1
#define REGNUM_MVEA_CR_MVEA_IPE_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_CMPRS_BUSY 0x00000004
#define SHIFT_MVEA_CR_MVEA_CMPRS_BUSY 2
#define REGNUM_MVEA_CR_MVEA_CMPRS_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_JMCOMP_BUSY 0x00000008
#define SHIFT_MVEA_CR_MVEA_JMCOMP_BUSY 3
#define REGNUM_MVEA_CR_MVEA_JMCOMP_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_EDMA_BUSY 0x00000010
#define SHIFT_MVEA_CR_MVEA_EDMA_BUSY 4
#define REGNUM_MVEA_CR_MVEA_EDMA_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_TDMA_BUSY 0x00000020
#define SHIFT_MVEA_CR_MVEA_TDMA_BUSY 5
#define REGNUM_MVEA_CR_MVEA_TDMA_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_DEB_BUSY  0x00000040
#define SHIFT_MVEA_CR_MVEA_DEB_BUSY 6
#define REGNUM_MVEA_CR_MVEA_DEB_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_VLC_BUSY  0x00000080
#define SHIFT_MVEA_CR_MVEA_VLC_BUSY 7
#define REGNUM_MVEA_CR_MVEA_VLC_BUSY 0x0018

#define MASK_MVEA_CR_MVEA_SPE_LRB_BUSY 0x00000100
#define SHIFT_MVEA_CR_MVEA_SPE_LRB_BUSY 8
#define REGNUM_MVEA_CR_MVEA_SPE_LRB_BUSY 0x0018

/* Register CR_MVEA_DMACMDFIFO_WAIT */
#define MVEA_CR_MVEA_DMACMDFIFO_WAIT 0x001C
#define MASK_MVEA_CR_MVEA_DCF_WAIT_SPE 0x00000001
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_SPE 0
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_SPE 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_IPE 0x00000002
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_IPE 1
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_IPE 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_CMPRS 0x00000004
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_CMPRS 2
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_CMPRS 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_JMCOMP 0x00000008
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_JMCOMP 3
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_JMCOMP 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_EDMA 0x00000010
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_EDMA 4
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_EDMA 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_TDMA 0x00000020
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_TDMA 5
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_TDMA 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_SW0 0x00000040
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_SW0 6
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_SW0 0x001C

#define MASK_MVEA_CR_MVEA_DCF_WAIT_SW1 0x00000080
#define SHIFT_MVEA_CR_MVEA_DCF_WAIT_SW1 7
#define REGNUM_MVEA_CR_MVEA_DCF_WAIT_SW1 0x001C

/* Register CR_MVEA_DMACMDFIFO_STATUS */
#define MVEA_CR_MVEA_DMACMDFIFO_STATUS 0x0020
#define MASK_MVEA_CR_MVEA_DCF_SPACE 0x0000003F
#define SHIFT_MVEA_CR_MVEA_DCF_SPACE 0
#define REGNUM_MVEA_CR_MVEA_DCF_SPACE 0x0020

#define MASK_MVEA_CR_MVEA_DCF_EMPTY 0x00000100
#define SHIFT_MVEA_CR_MVEA_DCF_EMPTY 8
#define REGNUM_MVEA_CR_MVEA_DCF_EMPTY 0x0020

/* Register CR_MVEA_AUTO_CLOCK_GATING */
#define MVEA_CR_MVEA_AUTO_CLOCK_GATING 0x0024
#define MASK_MVEA_CR_MVEA_SPE_AUTO_CLK_GATE 0x00000001
#define SHIFT_MVEA_CR_MVEA_SPE_AUTO_CLK_GATE 0
#define REGNUM_MVEA_CR_MVEA_SPE_AUTO_CLK_GATE 0x0024

#define MASK_MVEA_CR_MVEA_IPE_AUTO_CLK_GATE 0x00000002
#define SHIFT_MVEA_CR_MVEA_IPE_AUTO_CLK_GATE 1
#define REGNUM_MVEA_CR_MVEA_IPE_AUTO_CLK_GATE 0x0024

#define MASK_MVEA_CR_MVEA_CMPRS_AUTO_CLK_GATE 0x00000004
#define SHIFT_MVEA_CR_MVEA_CMPRS_AUTO_CLK_GATE 2
#define REGNUM_MVEA_CR_MVEA_CMPRS_AUTO_CLK_GATE 0x0024

#define MASK_MVEA_CR_MVEA_JMCOMP_AUTO_CLK_GATE 0x00000008
#define SHIFT_MVEA_CR_MVEA_JMCOMP_AUTO_CLK_GATE 3
#define REGNUM_MVEA_CR_MVEA_JMCOMP_AUTO_CLK_GATE 0x0024

/* Register CR_MVEA_MAN_CLOCK_GATING */
#define MVEA_CR_MVEA_MAN_CLOCK_GATING 0x0028
#define MASK_MVEA_CR_MVEA_SPE_MAN_CLK_GATE 0x00000001
#define SHIFT_MVEA_CR_MVEA_SPE_MAN_CLK_GATE 0
#define REGNUM_MVEA_CR_MVEA_SPE_MAN_CLK_GATE 0x0028

#define MASK_MVEA_CR_MVEA_IPE_MAN_CLK_GATE 0x00000002
#define SHIFT_MVEA_CR_MVEA_IPE_MAN_CLK_GATE 1
#define REGNUM_MVEA_CR_MVEA_IPE_MAN_CLK_GATE 0x0028

#define MASK_MVEA_CR_MVEA_CMPRS_MAN_CLK_GATE 0x00000004
#define SHIFT_MVEA_CR_MVEA_CMPRS_MAN_CLK_GATE 2
#define REGNUM_MVEA_CR_MVEA_CMPRS_MAN_CLK_GATE 0x0028

#define MASK_MVEA_CR_MVEA_JMCOMP_MAN_CLK_GATE 0x00000008
#define SHIFT_MVEA_CR_MVEA_JMCOMP_MAN_CLK_GATE 3
#define REGNUM_MVEA_CR_MVEA_JMCOMP_MAN_CLK_GATE 0x0028

#define MASK_MVEA_CR_MVEA_CMC_MAN_CLK_GATE 0x00000010
#define SHIFT_MVEA_CR_MVEA_CMC_MAN_CLK_GATE 4
#define REGNUM_MVEA_CR_MVEA_CMC_MAN_CLK_GATE 0x0028

/* Register CR_CMC_ESB_DIAGNOSTICS */
#define MVEA_CR_CMC_ESB_DIAGNOSTICS 0x0100
#define MASK_MVEA_CR_CMC_ESB_DIAGNOSTICS1 0xFFFFFFFF
#define SHIFT_MVEA_CR_CMC_ESB_DIAGNOSTICS1 0
#define REGNUM_MVEA_CR_CMC_ESB_DIAGNOSTICS1 0x0100

/* Register CR_CMC_DMA_DIAGNOSTICS */
#define MVEA_CR_CMC_DMA_DIAGNOSTICS 0x0104
#define MASK_MVEA_CR_CMC_DMA_DIAGNOSTICS 0xFFFFFFFF
#define SHIFT_MVEA_CR_CMC_DMA_DIAGNOSTICS 0
#define REGNUM_MVEA_CR_CMC_DMA_DIAGNOSTICS 0x0104

/* Register CR_CMC_SIGNATURE_ENC_MEM_WDATA */
#define MVEA_CR_CMC_SIGNATURE_ENC_MEM_WDATA 0x0108
#define MASK_MVEA_CR_CMC_SIGNATURE_ENC_MEM_WDATA 0xFFFFFFFF
#define SHIFT_MVEA_CR_CMC_SIGNATURE_ENC_MEM_WDATA 0
#define REGNUM_MVEA_CR_CMC_SIGNATURE_ENC_MEM_WDATA 0x0108

/* Register CR_CMC_SIGNATURE_ENC_MEM_ADDR */
#define MVEA_CR_CMC_SIGNATURE_ENC_MEM_ADDR 0x010C
#define MASK_MVEA_CR_CMC_SIGNATURE_ENC_MEM_ADDR 0xFFFFFFFF
#define SHIFT_MVEA_CR_CMC_SIGNATURE_ENC_MEM_ADDR 0
#define REGNUM_MVEA_CR_CMC_SIGNATURE_ENC_MEM_ADDR 0x010C

/* Register CR_CMC_PROC_ESB_ACCESS */
#define MVEA_CR_CMC_PROC_ESB_ACCESS 0x011C
#define MASK_MVEA_CR_CMC_PROC_ESB_REGION_NUMBER 0x0000001F
#define SHIFT_MVEA_CR_CMC_PROC_ESB_REGION_NUMBER 0
#define REGNUM_MVEA_CR_CMC_PROC_ESB_REGION_NUMBER 0x011C

/* Register CR_CMC_LRB_LOGICAL_OFFSET */
#define MVEA_CR_CMC_LRB_LOGICAL_OFFSET 0x012C
#define MASK_MVEA_CR_CMC_LRB_LOGICAL_OFFSET 0x0000001F
#define SHIFT_MVEA_CR_CMC_LRB_LOGICAL_OFFSET 0
#define REGNUM_MVEA_CR_CMC_LRB_LOGICAL_OFFSET 0x012C

/* Register CR_CMPRS_ACKNOWLEDGE */
#define MVEA_CR_CMPRS_ACKNOWLEDGE   0x0180
#define MASK_MVEA_CR_CMPRS_ACK      0x00000001
#define SHIFT_MVEA_CR_CMPRS_ACK     0
#define REGNUM_MVEA_CR_CMPRS_ACK    0x0180

/* Register CR_CMPRS_SBLK_THRESHOLD */
#define MVEA_CR_CMPRS_SBLK_THRESHOLD 0x0184
#define MASK_MVEA_CR_CMPRS_SBLK_THRSHLD 0x000001FF
#define SHIFT_MVEA_CR_CMPRS_SBLK_THRSHLD 0
#define REGNUM_MVEA_CR_CMPRS_SBLK_THRSHLD 0x0184

/* Register CR_CMPRS_COEFF_COST_H */
#define MVEA_CR_CMPRS_COEFF_COST_H  0x0188
#define MASK_MVEA_CR_CMPRS_COEFF_COST8 0x0000000F
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST8 0
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST8 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST9 0x000000F0
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST9 4
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST9 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST10 0x00000F00
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST10 8
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST10 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST11 0x0000F000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST11 12
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST11 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST12 0x000F0000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST12 16
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST12 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST13 0x00F00000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST13 20
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST13 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST14 0x0F000000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST14 24
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST14 0x0188

#define MASK_MVEA_CR_CMPRS_COEFF_COST15 0xF0000000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST15 28
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST15 0x0188

/* Register CR_CMPRS_COEFF_COST_L */
#define MVEA_CR_CMPRS_COEFF_COST_L  0x018C
#define MASK_MVEA_CR_CMPRS_COEFF_COST0 0x0000000F
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST0 0
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST0 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST1 0x000000F0
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST1 4
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST1 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST2 0x00000F00
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST2 8
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST2 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST3 0x0000F000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST3 12
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST3 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST4 0x000F0000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST4 16
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST4 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST5 0x00F00000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST5 20
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST5 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST6 0x0F000000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST6 24
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST6 0x018C

#define MASK_MVEA_CR_CMPRS_COEFF_COST7 0xF0000000
#define SHIFT_MVEA_CR_CMPRS_COEFF_COST7 28
#define REGNUM_MVEA_CR_CMPRS_COEFF_COST7 0x018C

/* Register CR_CMPRS_COEFF_THRESHOLD */
#define MVEA_CR_CMPRS_COEFF_THRESHOLD 0x0190
#define MASK_MVEA_CR_CMPRS_COEFF_THRSHLD 0x0000FFFF
#define SHIFT_MVEA_CR_CMPRS_COEFF_THRSHLD 0
#define REGNUM_MVEA_CR_CMPRS_COEFF_THRSHLD 0x0190

/* Register CR_CMPRS_SBLK_RIGHT */
#define MVEA_CR_CMPRS_SBLK_RIGHT    0x0194
#define MASK_MVEA_CR_CMPRS_SBLK_RIGHT 0xFFFFFFFF
#define SHIFT_MVEA_CR_CMPRS_SBLK_RIGHT 0
#define REGNUM_MVEA_CR_CMPRS_SBLK_RIGHT 0x0194

/* Register CR_CMPRS_SBLK_BOTTOM */
#define MVEA_CR_CMPRS_SBLK_BOTTOM   0x0198
#define MASK_MVEA_CR_CMPRS_SBLK_BOTTOM 0x00FFFFFF
#define SHIFT_MVEA_CR_CMPRS_SBLK_BOTTOM 0
#define REGNUM_MVEA_CR_CMPRS_SBLK_BOTTOM 0x0198

/* Register CR_CMPRS_TRANS_CRC */
#define MVEA_CR_CMPRS_TRANS_CRC     0x019C
#define MASK_MVEA_CR_CMPRS_IT_CRC   0x0000FFFF
#define SHIFT_MVEA_CR_CMPRS_IT_CRC  0
#define REGNUM_MVEA_CR_CMPRS_IT_CRC 0x019C

#define MASK_MVEA_CR_CMPRS_FT_CRC   0xFFFF0000
#define SHIFT_MVEA_CR_CMPRS_FT_CRC  16
#define REGNUM_MVEA_CR_CMPRS_FT_CRC 0x019C

/* Register CR_CMPRS_QUANT_CRC */
#define MVEA_CR_CMPRS_QUANT_CRC     0x01A0
#define MASK_MVEA_CR_CMPRS_IQT_CRC  0x0000FFFF
#define SHIFT_MVEA_CR_CMPRS_IQT_CRC 0
#define REGNUM_MVEA_CR_CMPRS_IQT_CRC 0x01A0

#define MASK_MVEA_CR_CMPRS_QT_CRC   0xFFFF0000
#define SHIFT_MVEA_CR_CMPRS_QT_CRC  16
#define REGNUM_MVEA_CR_CMPRS_QT_CRC 0x01A0

/* Register CR_CMPRS_DIAGNOSTIC1 */
#define MVEA_CR_CMPRS_DIAGNOSTIC1   0x01A4
#define MASK_MVEA_CR_CMPRS_DIAG1    0xFFFFFFFF
#define SHIFT_MVEA_CR_CMPRS_DIAG1   0
#define REGNUM_MVEA_CR_CMPRS_DIAG1  0x01A4

/* Register CR_CMPRS_RLE_CONTROL */
#define MVEA_CR_CMPRS_RLE_CONTROL   0x01A8
#define MASK_MVEA_CR_CMPRS_RLE_ENABLE 0x80000000
#define SHIFT_MVEA_CR_CMPRS_RLE_ENABLE 31
#define REGNUM_MVEA_CR_CMPRS_RLE_ENABLE 0x01A8

/* Register CR_CMPRS_RLE_STATUS */
#define MVEA_CR_CMPRS_RLE_STATUS    0x01AC
#define MASK_MVEA_CR_CMPRS_CODED_COUNT 0x000007FF
#define SHIFT_MVEA_CR_CMPRS_CODED_COUNT 0
#define REGNUM_MVEA_CR_CMPRS_CODED_COUNT 0x01AC

/* Register CR_CMPRS_MAX_CYCLE_COUNT */
#define MVEA_CR_CMPRS_MAX_CYCLE_COUNT 0x01B0
#define MASK_MVEA_CR_CMPRS_MAX_CYCLE_COUNT 0x0000FFFF
#define SHIFT_MVEA_CR_CMPRS_MAX_CYCLE_COUNT 0
#define REGNUM_MVEA_CR_CMPRS_MAX_CYCLE_COUNT 0x01B0

/* Register CR_CMPRS_MAX_CYCLE_MB */
#define MVEA_CR_CMPRS_MAX_CYCLE_MB  0x01B4
#define MASK_MVEA_CR_CMPRS_MAX_CYCLE_MB_NUM 0x003FFFFF
#define SHIFT_MVEA_CR_CMPRS_MAX_CYCLE_MB_NUM 0
#define REGNUM_MVEA_CR_CMPRS_MAX_CYCLE_MB_NUM 0x01B4

#define MASK_MVEA_CR_CMPRS_MAX_CYCLE_MB_TYPE 0x30000000
#define SHIFT_MVEA_CR_CMPRS_MAX_CYCLE_MB_TYPE 28
#define REGNUM_MVEA_CR_CMPRS_MAX_CYCLE_MB_TYPE 0x01B4

/* Register CR_CMPRS_MAX_CYCLE_RESET */
#define MVEA_CR_CMPRS_MAX_CYCLE_RESET 0x01B8
#define MASK_MVEA_CR_CMPRS_MAX_CYCLE_RESET 0x00000001
#define SHIFT_MVEA_CR_CMPRS_MAX_CYCLE_RESET 0
#define REGNUM_MVEA_CR_CMPRS_MAX_CYCLE_RESET 0x01B8

#define MASK_MVEA_CR_CMPRS_DISABLE_COUNTERS 0x00000002
#define SHIFT_MVEA_CR_CMPRS_DISABLE_COUNTERS 1
#define REGNUM_MVEA_CR_CMPRS_DISABLE_COUNTERS 0x01B8

/* Register CR_CMPRS_VLC_CRC */
#define MVEA_CR_CMPRS_VLC_CRC       0x01BC
#define MASK_MVEA_CR_CMPRS_VLC_CRC  0x0000FFFF
#define SHIFT_MVEA_CR_CMPRS_VLC_CRC 0
#define REGNUM_MVEA_CR_CMPRS_VLC_CRC 0x01BC

/* Register CR_IPE_PERFORMANCE_LAMBDA */
#define MVEA_CR_IPE_PERFORMANCE_LAMBDA 0x01F8
#define MASK_MVEA_CR_IPE_LAMBDA_B   0x000000FF
#define SHIFT_MVEA_CR_IPE_LAMBDA_B  0
#define REGNUM_MVEA_CR_IPE_LAMBDA_B 0x01F8

#define MASK_MVEA_CR_IPE_LAMBDA_A   0x0000FF00
#define SHIFT_MVEA_CR_IPE_LAMBDA_A  8
#define REGNUM_MVEA_CR_IPE_LAMBDA_A 0x01F8

/* Register CR_IPE_PERFORMANCE_QP */
#define MVEA_CR_IPE_PERFORMANCE_QP  0x01FC
#define MASK_MVEA_CR_IPE_QP_B       0x000000FF
#define SHIFT_MVEA_CR_IPE_QP_B      0
#define REGNUM_MVEA_CR_IPE_QP_B     0x01FC

#define MASK_MVEA_CR_IPE_QP_A       0x0000FF00
#define SHIFT_MVEA_CR_IPE_QP_A      8
#define REGNUM_MVEA_CR_IPE_QP_A     0x01FC

/* Register CR_IPE_CONTROL */
#define MVEA_CR_IPE_CONTROL         0x0200
#define MASK_MVEA_CR_IPE_BLOCKSIZE  0x00000003
#define SHIFT_MVEA_CR_IPE_BLOCKSIZE 0
#define REGNUM_MVEA_CR_IPE_BLOCKSIZE 0x0200

#define MASK_MVEA_CR_IPE_Y_CANDIDATE_NUM 0x0000003C
#define SHIFT_MVEA_CR_IPE_Y_CANDIDATE_NUM 2
#define REGNUM_MVEA_CR_IPE_Y_CANDIDATE_NUM 0x0200

#define MASK_MVEA_CR_IPE_Y_FINE_SEARCH 0x00000040
#define SHIFT_MVEA_CR_IPE_Y_FINE_SEARCH 6
#define REGNUM_MVEA_CR_IPE_Y_FINE_SEARCH 0x0200

#define MASK_MVEA_CR_IPE_GRID_SEARCH_SIZE 0x00000380
#define SHIFT_MVEA_CR_IPE_GRID_SEARCH_SIZE 7
#define REGNUM_MVEA_CR_IPE_GRID_SEARCH_SIZE 0x0200

#define MASK_MVEA_CR_IPE_GRID_FINE_SEARCH 0x00000C00
#define SHIFT_MVEA_CR_IPE_GRID_FINE_SEARCH 10
#define REGNUM_MVEA_CR_IPE_GRID_FINE_SEARCH 0x0200

#define MASK_MVEA_CR_IPE_ENCODING_FORMAT 0x00003000
#define SHIFT_MVEA_CR_IPE_ENCODING_FORMAT 12
#define REGNUM_MVEA_CR_IPE_ENCODING_FORMAT 0x0200

/* Register CR_IPE_SEARCH_STATUS */
#define MVEA_CR_IPE_SEARCH_STATUS   0x0204
#define MASK_MVEA_CR_IPE_SEARCH_STATUS 0x00000007
#define SHIFT_MVEA_CR_IPE_SEARCH_STATUS 0
#define REGNUM_MVEA_CR_IPE_SEARCH_STATUS 0x0204

/* Register CR_IPE_INT_MVCOST */
#define MVEA_CR_IPE_INT_MVCOST      0x0208
#define MASK_MVEA_CR_IPE_INT_MVCOST 0x0000FFFF
#define SHIFT_MVEA_CR_IPE_INT_MVCOST 0
#define REGNUM_MVEA_CR_IPE_INT_MVCOST 0x0208

/* Register CR_IPE_MB_SAD */
#define MVEA_CR_IPE_MB_SAD          0x020C
#define MASK_MVEA_CR_IPE_MB_SAD     0x0000FFFF
#define SHIFT_MVEA_CR_IPE_MB_SAD    0
#define REGNUM_MVEA_CR_IPE_MB_SAD   0x020C

/* Register CR_IPE_DIAG1 */
#define MVEA_CR_IPE_DIAG1           0x0210
#define MASK_MVEA_CR_IPE_DIAG1      0xFFFFFFFF
#define SHIFT_MVEA_CR_IPE_DIAG1     0
#define REGNUM_MVEA_CR_IPE_DIAG1    0x0210

/* Register CR_IPE_JITTER_TABLE_0 */
#define MVEA_CR_IPE_JITTER_TABLE_0  0x0220
#define MASK_MVEA_CR_IPE_JITTER_TABLE_0_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_0_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_0_X 0x0220

#define MASK_MVEA_CR_IPE_JITTER_TABLE_0_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_0_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_0_Y 0x0220

/* Register CR_IPE_JITTER_TABLE_1 */
#define MVEA_CR_IPE_JITTER_TABLE_1  0x0224
#define MASK_MVEA_CR_IPE_JITTER_TABLE_1_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_1_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_1_X 0x0224

#define MASK_MVEA_CR_IPE_JITTER_TABLE_1_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_1_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_1_Y 0x0224

/* Register CR_IPE_JITTER_TABLE_2 */
#define MVEA_CR_IPE_JITTER_TABLE_2  0x0228
#define MASK_MVEA_CR_IPE_JITTER_TABLE_2_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_2_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_2_X 0x0228

#define MASK_MVEA_CR_IPE_JITTER_TABLE_2_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_2_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_2_Y 0x0228

/* Register CR_IPE_JITTER_TABLE_3 */
#define MVEA_CR_IPE_JITTER_TABLE_3  0x022C
#define MASK_MVEA_CR_IPE_JITTER_TABLE_3_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_3_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_3_X 0x022C

#define MASK_MVEA_CR_IPE_JITTER_TABLE_3_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_3_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_3_Y 0x022C

/* Register CR_IPE_JITTER_TABLE_4 */
#define MVEA_CR_IPE_JITTER_TABLE_4  0x0230
#define MASK_MVEA_CR_IPE_JITTER_TABLE_4_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_4_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_4_X 0x0230

#define MASK_MVEA_CR_IPE_JITTER_TABLE_4_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_4_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_4_Y 0x0230

/* Register CR_IPE_JITTER_TABLE_5 */
#define MVEA_CR_IPE_JITTER_TABLE_5  0x0234
#define MASK_MVEA_CR_IPE_JITTER_TABLE_5_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_5_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_5_X 0x0234

#define MASK_MVEA_CR_IPE_JITTER_TABLE_5_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_5_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_5_Y 0x0234

/* Register CR_IPE_JITTER_TABLE_6 */
#define MVEA_CR_IPE_JITTER_TABLE_6  0x0238
#define MASK_MVEA_CR_IPE_JITTER_TABLE_6_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_6_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_6_X 0x0238

#define MASK_MVEA_CR_IPE_JITTER_TABLE_6_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_6_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_6_Y 0x0238

/* Register CR_IPE_JITTER_TABLE_7 */
#define MVEA_CR_IPE_JITTER_TABLE_7  0x023C
#define MASK_MVEA_CR_IPE_JITTER_TABLE_7_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_7_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_7_X 0x023C

#define MASK_MVEA_CR_IPE_JITTER_TABLE_7_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_7_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_7_Y 0x023C

/* Register CR_IPE_JITTER_TABLE_8 */
#define MVEA_CR_IPE_JITTER_TABLE_8  0x0240
#define MASK_MVEA_CR_IPE_JITTER_TABLE_8_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_8_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_8_X 0x0240

#define MASK_MVEA_CR_IPE_JITTER_TABLE_8_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_8_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_8_Y 0x0240

/* Register CR_IPE_JITTER_TABLE_9 */
#define MVEA_CR_IPE_JITTER_TABLE_9  0x0244
#define MASK_MVEA_CR_IPE_JITTER_TABLE_9_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_9_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_9_X 0x0244

#define MASK_MVEA_CR_IPE_JITTER_TABLE_9_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_9_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_9_Y 0x0244

/* Register CR_IPE_JITTER_TABLE_10 */
#define MVEA_CR_IPE_JITTER_TABLE_10 0x0248
#define MASK_MVEA_CR_IPE_JITTER_TABLE_10_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_10_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_10_X 0x0248

#define MASK_MVEA_CR_IPE_JITTER_TABLE_10_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_10_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_10_Y 0x0248

/* Register CR_IPE_JITTER_TABLE_11 */
#define MVEA_CR_IPE_JITTER_TABLE_11 0x024C
#define MASK_MVEA_CR_IPE_JITTER_TABLE_11_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_11_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_11_X 0x024C

#define MASK_MVEA_CR_IPE_JITTER_TABLE_11_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_11_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_11_Y 0x024C

/* Register CR_IPE_JITTER_TABLE_12 */
#define MVEA_CR_IPE_JITTER_TABLE_12 0x0250
#define MASK_MVEA_CR_IPE_JITTER_TABLE_12_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_12_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_12_X 0x0250

#define MASK_MVEA_CR_IPE_JITTER_TABLE_12_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_12_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_12_Y 0x0250

/* Register CR_IPE_JITTER_TABLE_13 */
#define MVEA_CR_IPE_JITTER_TABLE_13 0x0254
#define MASK_MVEA_CR_IPE_JITTER_TABLE_13_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_13_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_13_X 0x0254

#define MASK_MVEA_CR_IPE_JITTER_TABLE_13_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_13_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_13_Y 0x0254

/* Register CR_IPE_JITTER_TABLE_14 */
#define MVEA_CR_IPE_JITTER_TABLE_14 0x0258
#define MASK_MVEA_CR_IPE_JITTER_TABLE_14_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_14_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_14_X 0x0258

#define MASK_MVEA_CR_IPE_JITTER_TABLE_14_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_14_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_14_Y 0x0258

/* Register CR_IPE_JITTER_TABLE_15 */
#define MVEA_CR_IPE_JITTER_TABLE_15 0x025C
#define MASK_MVEA_CR_IPE_JITTER_TABLE_15_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_15_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_15_X 0x025C

#define MASK_MVEA_CR_IPE_JITTER_TABLE_15_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_15_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_15_Y 0x025C

/* Register CR_IPE_JITTER_TABLE_16 */
#define MVEA_CR_IPE_JITTER_TABLE_16 0x0260
#define MASK_MVEA_CR_IPE_JITTER_TABLE_16_X 0x0000001F
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_16_X 0
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_16_X 0x0260

#define MASK_MVEA_CR_IPE_JITTER_TABLE_16_Y 0x00001F00
#define SHIFT_MVEA_CR_IPE_JITTER_TABLE_16_Y 8
#define REGNUM_MVEA_CR_IPE_JITTER_TABLE_16_Y 0x0260

/* Register CR_IPE_CTRL_CRC */
#define MVEA_CR_IPE_CTRL_CRC        0x0264
#define MASK_MVEA_CR_IPE_CTRL_CRC   0xFFFFFFFF
#define SHIFT_MVEA_CR_IPE_CTRL_CRC  0
#define REGNUM_MVEA_CR_IPE_CTRL_CRC 0x0264

/* Register CR_IPE_WDATA_CRC */
#define MVEA_CR_IPE_WDATA_CRC       0x0268
#define MASK_MVEA_CR_IPE_WDATA_CRC  0xFFFFFFFF
#define SHIFT_MVEA_CR_IPE_WDATA_CRC 0
#define REGNUM_MVEA_CR_IPE_WDATA_CRC 0x0268

/* Register CR_IPE_MB_PERFORMANCE_CLEAR */
#define MVEA_CR_IPE_MB_PERFORMANCE_CLEAR 0x026C
#define MASK_MVEA_CR_IPE_MB_PERFORMANCE_CLEAR 0x00000001
#define SHIFT_MVEA_CR_IPE_MB_PERFORMANCE_CLEAR 0
#define REGNUM_MVEA_CR_IPE_MB_PERFORMANCE_CLEAR 0x026C

/* Register CR_IPE_MB_PERFORMANCE_RESULT */
#define MVEA_CR_IPE_MB_PERFORMANCE_RESULT 0x0270
#define MASK_MVEA_CR_IPE_MB_PERFORMANCE_RESULT 0x0000FFFF
#define SHIFT_MVEA_CR_IPE_MB_PERFORMANCE_RESULT 0
#define REGNUM_MVEA_CR_IPE_MB_PERFORMANCE_RESULT 0x0270

/* Register CR_IPE_MB_PERFORMANCE_MB_NUMBER */
#define MVEA_CR_IPE_MB_PERFORMANCE_MB_NUMBER 0x0274
#define MASK_MVEA_CR_IPE_MB_PERFORMANCE_MB_NUMBER 0x003FFFFF
#define SHIFT_MVEA_CR_IPE_MB_PERFORMANCE_MB_NUMBER 0
#define REGNUM_MVEA_CR_IPE_MB_PERFORMANCE_MB_NUMBER 0x0274

/* Register CR_IPE_VECTOR_CLIPPING */
#define MVEA_CR_IPE_VECTOR_CLIPPING 0x0278
#define MASK_MVEA_CR_IPE_VECTOR_CLIPPING_Y 0x000000FF
#define SHIFT_MVEA_CR_IPE_VECTOR_CLIPPING_Y 0
#define REGNUM_MVEA_CR_IPE_VECTOR_CLIPPING_Y 0x0278

#define MASK_MVEA_CR_IPE_VECTOR_CLIPPING_X 0x0000FF00
#define SHIFT_MVEA_CR_IPE_VECTOR_CLIPPING_X 8
#define REGNUM_MVEA_CR_IPE_VECTOR_CLIPPING_X 0x0278

/* Register CR_JMCOMP_CONTROL */
#define MVEA_CR_JMCOMP_CONTROL      0x0280
#define MASK_MVEA_CR_JMCOMP_MODE    0x00000003
#define SHIFT_MVEA_CR_JMCOMP_MODE   0
#define REGNUM_MVEA_CR_JMCOMP_MODE  0x0280

#define MASK_MVEA_CR_JMCOMP_AC_ENABLE 0x00008000
#define SHIFT_MVEA_CR_JMCOMP_AC_ENABLE 15
#define REGNUM_MVEA_CR_JMCOMP_AC_ENABLE 0x0280

#define MASK_MVEA_CR_JMCOMP_JPEG_NUM_BLOCKS 0x00F00000
#define SHIFT_MVEA_CR_JMCOMP_JPEG_NUM_BLOCKS 20
#define REGNUM_MVEA_CR_JMCOMP_JPEG_NUM_BLOCKS 0x0280

#define MASK_MVEA_CR_JMCOMP_DISABLE_QP_PATCH_ON_SKIP 0x01000000
#define SHIFT_MVEA_CR_JMCOMP_DISABLE_QP_PATCH_ON_SKIP 24
#define REGNUM_MVEA_CR_JMCOMP_DISABLE_QP_PATCH_ON_SKIP 0x0280

/* Register CR_JMCOMP_JPEG_BLOCK_TYPES */
#define MVEA_CR_JMCOMP_JPEG_BLOCK_TYPES 0x0284
#define MASK_MVEA_CR_JMCOMP_JPEG_BLOCK_TYPE(i) (0x00000003 << (0 + ((i) * 2)))
#define SHIFT_MVEA_CR_JMCOMP_JPEG_BLOCK_TYPE(i) (0 + ((i) * 2))
#define REGNUM_MVEA_CR_JMCOMP_JPEG_BLOCK_TYPE(i) 0x0284

/* Register CR_JMCOMP_JPEG_LUMA_PRED */
#define MVEA_CR_JMCOMP_JPEG_LUMA_PRED 0x0288
#define MASK_MVEA_CR_JMCOMP_JPEG_DC_LUMA_PRED 0x00000FFF
#define SHIFT_MVEA_CR_JMCOMP_JPEG_DC_LUMA_PRED 0
#define REGNUM_MVEA_CR_JMCOMP_JPEG_DC_LUMA_PRED 0x0288

/* Register CR_JMCOMP_JPEG_CHROMA_PREDS */
#define MVEA_CR_JMCOMP_JPEG_CHROMA_PREDS 0x028C
#define MASK_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_V_PRED 0x0FFF0000
#define SHIFT_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_V_PRED 16
#define REGNUM_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_V_PRED 0x028C

#define MASK_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_U_PRED 0x00000FFF
#define SHIFT_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_U_PRED 0
#define REGNUM_MVEA_CR_JMCOMP_JPEG_DC_CHROMA_U_PRED 0x028C

/* Register CR_JMCOMP_CRC */
#define MVEA_CR_JMCOMP_CRC          0x0314
#define MASK_MVEA_CR_JMCOMP_CRC_OUT 0xFFFFFFFF
#define SHIFT_MVEA_CR_JMCOMP_CRC_OUT 0
#define REGNUM_MVEA_CR_JMCOMP_CRC_OUT 0x0314

/* Register CR_JMCOMP_VLC_CRC */
#define MVEA_CR_JMCOMP_VLC_CRC      0x0318
#define MASK_MVEA_CR_JMCOMP_VLC_IF_CRC 0xFFFFFFFF
#define SHIFT_MVEA_CR_JMCOMP_VLC_IF_CRC 0
#define REGNUM_MVEA_CR_JMCOMP_VLC_IF_CRC 0x0318

/* Register CR_JMCOMP_PERFORMANCE_0 */
#define MVEA_CR_JMCOMP_PERFORMANCE_0 0x031C
#define MASK_MVEA_CR_JMCOMP_WORST_MB_CYCLES 0x0000FFFF
#define SHIFT_MVEA_CR_JMCOMP_WORST_MB_CYCLES 0
#define REGNUM_MVEA_CR_JMCOMP_WORST_MB_CYCLES 0x031C

#define MASK_MVEA_CR_JMCOMP_WORST_MB_TYPE 0x00030000
#define SHIFT_MVEA_CR_JMCOMP_WORST_MB_TYPE 16
#define REGNUM_MVEA_CR_JMCOMP_WORST_MB_TYPE 0x031C

/* Register CR_JMCOMP_PERFORMANCE_1 */
#define MVEA_CR_JMCOMP_PERFORMANCE_1 0x0320
#define MASK_MVEA_CR_JMCOMP_WORST_MB_NUM 0x003FFFFF
#define SHIFT_MVEA_CR_JMCOMP_WORST_MB_NUM 0
#define REGNUM_MVEA_CR_JMCOMP_WORST_MB_NUM 0x0320

/* Register CR_JMCOMP_PERFORMANCE_2 */
#define MVEA_CR_JMCOMP_PERFORMANCE_2 0x0324
#define MASK_MVEA_CR_JMCOMP_WORST_MB_RESET 0x00000001
#define SHIFT_MVEA_CR_JMCOMP_WORST_MB_RESET 0
#define REGNUM_MVEA_CR_JMCOMP_WORST_MB_RESET 0x0324

#define MASK_MVEA_CR_JMCOMP_DISABLE_COUNTERS 0x00000002
#define SHIFT_MVEA_CR_JMCOMP_DISABLE_COUNTERS 1
#define REGNUM_MVEA_CR_JMCOMP_DISABLE_COUNTERS 0x0324

/* Register CR_JMCOMP_QP_VALUE */
#define MVEA_CR_JMCOMP_QP_VALUE     0x0348
#define MASK_MVEA_CR_JMCOMP_REAL_QP_LUMA 0x000001FF
#define SHIFT_MVEA_CR_JMCOMP_REAL_QP_LUMA 0
#define REGNUM_MVEA_CR_JMCOMP_REAL_QP_LUMA 0x0348

/* Register CR_SPE_CONTROL */
#define MVEA_CR_SPE_CONTROL         0x0380
#define MASK_MVEA_CR_SPE_INTER_ENABLE 0x00000001
#define SHIFT_MVEA_CR_SPE_INTER_ENABLE 0
#define REGNUM_MVEA_CR_SPE_INTER_ENABLE 0x0380

#define MASK_MVEA_CR_SPE_INTRA_ENABLE 0x00000002
#define SHIFT_MVEA_CR_SPE_INTRA_ENABLE 1
#define REGNUM_MVEA_CR_SPE_INTRA_ENABLE 0x0380

#define MASK_MVEA_CR_SPE_MPEG4_ENABLE 0x00000004
#define SHIFT_MVEA_CR_SPE_MPEG4_ENABLE 2
#define REGNUM_MVEA_CR_SPE_MPEG4_ENABLE 0x0380

#define MASK_MVEA_CR_SPE_FORCE_SKIP 0x00000008
#define SHIFT_MVEA_CR_SPE_FORCE_SKIP 3
#define REGNUM_MVEA_CR_SPE_FORCE_SKIP 0x0380

#define MASK_MVEA_CR_SPE_H263_ENABLE 0x00000010
#define SHIFT_MVEA_CR_SPE_H263_ENABLE 4
#define REGNUM_MVEA_CR_SPE_H263_ENABLE 0x0380

/* Register CR_SPE_INTRA_COST */
#define MVEA_CR_SPE_INTRA_COST      0x0384
#define MASK_MVEA_CR_SPE_INTRA_COST 0x0001FFFF
#define SHIFT_MVEA_CR_SPE_INTRA_COST 0
#define REGNUM_MVEA_CR_SPE_INTRA_COST 0x0384

/* Register CR_SPE_ZERO_THRESH */
#define MVEA_CR_SPE_ZERO_THRESH     0x0388
#define MASK_MVEA_CR_SPE_ZERO_THRESH 0x000003FF
#define SHIFT_MVEA_CR_SPE_ZERO_THRESH 0
#define REGNUM_MVEA_CR_SPE_ZERO_THRESH 0x0388

/* Register CR_SPE_REQUEST */
#define MVEA_CR_SPE_REQUEST         0x038C
#define MASK_MVEA_CR_SPE_REQ        0x00000001
#define SHIFT_MVEA_CR_SPE_REQ       0
#define REGNUM_MVEA_CR_SPE_REQ      0x038C

/* Register CR_SPE_INTER_SUM_MIN_SADS */
#define MVEA_CR_SPE_INTER_SUM_MIN_SADS 0x0390
#define MASK_MVEA_CR_SPE_INTER_SUM_MIN_SADS 0x0000FFFF
#define SHIFT_MVEA_CR_SPE_INTER_SUM_MIN_SADS 0
#define REGNUM_MVEA_CR_SPE_INTER_SUM_MIN_SADS 0x0390

/* Register CR_SPE_DIAGNOSTIC1 */
#define MVEA_CR_SPE_DIAGNOSTIC1     0x0394
#define MASK_MVEA_CR_SPE_DIAG1      0xFFFFFFFF
#define SHIFT_MVEA_CR_SPE_DIAG1     0
#define REGNUM_MVEA_CR_SPE_DIAG1    0x0394

/* Register CR_SPE_INTER_SAD_SIGNATURE */
#define MVEA_CR_SPE_INTER_SAD_SIGNATURE 0x0398
#define MASK_MVEA_CR_SPE_INTER_SAD_SIGNATURE 0xFFFFFFFF
#define SHIFT_MVEA_CR_SPE_INTER_SAD_SIGNATURE 0
#define REGNUM_MVEA_CR_SPE_INTER_SAD_SIGNATURE 0x0398

/* Register CR_SPE_INTRA_SAD_SIGNATURE */
#define MVEA_CR_SPE_INTRA_SAD_SIGNATURE 0x039C
#define MASK_MVEA_CR_SPE_INTRA_SAD_SIGNATURE 0xFFFFFFFF
#define SHIFT_MVEA_CR_SPE_INTRA_SAD_SIGNATURE 0
#define REGNUM_MVEA_CR_SPE_INTRA_SAD_SIGNATURE 0x039C

/* Register CR_SPE_INTRA16_CONTROL */
#define MVEA_CR_SPE_INTRA16_CONTROL 0x03A0
#define MASK_MVEA_CR_SPE_INTRA16_BIAS 0x0003FFFF
#define SHIFT_MVEA_CR_SPE_INTRA16_BIAS 0
#define REGNUM_MVEA_CR_SPE_INTRA16_BIAS 0x03A0

#define MASK_MVEA_CR_SPE_INTRA16_DISABLE 0x80000000
#define SHIFT_MVEA_CR_SPE_INTRA16_DISABLE 31
#define REGNUM_MVEA_CR_SPE_INTRA16_DISABLE 0x03A0

/* Register CR_SPE_INT_MVCOST */
#define MVEA_CR_SPE_INT_MVCOST      0x03A4
#define MASK_MVEA_CR_SPE_MVCOST     0x0000FFFF
#define SHIFT_MVEA_CR_SPE_MVCOST    0
#define REGNUM_MVEA_CR_SPE_MVCOST   0x03A4

/* Register CR_SPE_INTER_BIAS_CONTROL */
#define MVEA_CR_SPE_INTER_BIAS_CONTROL 0x03A8
#define MASK_MVEA_CR_SPE_INTER_BIAS 0x0003FFFF
#define SHIFT_MVEA_CR_SPE_INTER_BIAS 0
#define REGNUM_MVEA_CR_SPE_INTER_BIAS 0x03A8

/* Register CR_IMG_MVEA_RSVD0 */
#define MVEA_CR_IMG_MVEA_RSVD0      0x03B0
#define MASK_MVEA_CR_IMG_MVEA_RESERVED0 0xFFFFFFFF
#define SHIFT_MVEA_CR_IMG_MVEA_RESERVED0 0
#define REGNUM_MVEA_CR_IMG_MVEA_RESERVED0 0x03B0

/* Register CR_IPE_PRED_VECTOR_BIAS */
#define MVEA_CR_IPE_PRED_VECTOR_BIAS 0x03B4
#define MASK_MVEA_CR_IPE_PRED_BIAS  0x00007FFF
#define SHIFT_MVEA_CR_IPE_PRED_BIAS 0
#define REGNUM_MVEA_CR_IPE_PRED_BIAS 0x03B4

/* Register CR_SPE_PRED_VECTOR_BIAS */
#define MVEA_CR_SPE_PRED_VECTOR_BIAS 0x03B8
#define MASK_MVEA_CR_SPE_PRED_BIAS  0x7FFF0000
#define SHIFT_MVEA_CR_SPE_PRED_BIAS 16
#define REGNUM_MVEA_CR_SPE_PRED_BIAS 0x03B8

#define MASK_MVEA_CR_SPE_PRED_ENABLE 0x80000000
#define SHIFT_MVEA_CR_SPE_PRED_ENABLE 31
#define REGNUM_MVEA_CR_SPE_PRED_ENABLE 0x03B8

/* Register CR_SPE_MB_COUNT */
#define MVEA_CR_SPE_MB_COUNT        0x03BC
#define MASK_MVEA_CR_SPE_INTER_MB_COUNT 0x03FF0000
#define SHIFT_MVEA_CR_SPE_INTER_MB_COUNT 16
#define REGNUM_MVEA_CR_SPE_INTER_MB_COUNT 0x03BC

#define MASK_MVEA_CR_SPE_INTRA_MB_COUNT 0x000003FF
#define SHIFT_MVEA_CR_SPE_INTRA_MB_COUNT 0
#define REGNUM_MVEA_CR_SPE_INTRA_MB_COUNT 0x03BC

/* Register CR_SPE_PRED_VECTOR */
#define MVEA_CR_SPE_PRED_VECTOR     0x03D4
#define MASK_MVEA_CR_SPE_PRED_VECTOR_Y 0x7FFF0000
#define SHIFT_MVEA_CR_SPE_PRED_VECTOR_Y 16
#define REGNUM_MVEA_CR_SPE_PRED_VECTOR_Y 0x03D4

#define MASK_MVEA_CR_SPE_PRED_VECTOR_X 0x00007FFF
#define SHIFT_MVEA_CR_SPE_PRED_VECTOR_X 0
#define REGNUM_MVEA_CR_SPE_PRED_VECTOR_X 0x03D4

/* Register CR_SPE_MAX_CYCLE_COUNT */
#define MVEA_CR_SPE_MAX_CYCLE_COUNT 0x03D8
#define MASK_MVEA_CR_SPE_MAX_CYCLE_COUNT 0x0000FFFF
#define SHIFT_MVEA_CR_SPE_MAX_CYCLE_COUNT 0
#define REGNUM_MVEA_CR_SPE_MAX_CYCLE_COUNT 0x03D8

/* Register CR_SPE_MAX_CYCLE_MB */
#define MVEA_CR_SPE_MAX_CYCLE_MB    0x03DC
#define MASK_MVEA_CR_SPE_MAX_CYCLE_MB_TYPE 0xC0000000
#define SHIFT_MVEA_CR_SPE_MAX_CYCLE_MB_TYPE 30
#define REGNUM_MVEA_CR_SPE_MAX_CYCLE_MB_TYPE 0x03DC

#define MASK_MVEA_CR_SPE_MAX_CYCLE_MB_NUM 0x003FFFFF
#define SHIFT_MVEA_CR_SPE_MAX_CYCLE_MB_NUM 0
#define REGNUM_MVEA_CR_SPE_MAX_CYCLE_MB_NUM 0x03DC

/* Register CR_SPE_INTRA_SUM_MIN_SADS */
#define MVEA_CR_SPE_INTRA_SUM_MIN_SADS 0x03E0
#define MASK_MVEA_CR_SPE_INTRA_SUM_MIN_SADS 0x0000FFFF
#define SHIFT_MVEA_CR_SPE_INTRA_SUM_MIN_SADS 0
#define REGNUM_MVEA_CR_SPE_INTRA_SUM_MIN_SADS 0x03E0

/* Register CR_SPE_MAX_CYCLE_RESET */
#define MVEA_CR_SPE_MAX_CYCLE_RESET 0x03E4
#define MASK_MVEA_CR_SPE_MAX_CYCLE_RESET 0x00000001
#define SHIFT_MVEA_CR_SPE_MAX_CYCLE_RESET 0
#define REGNUM_MVEA_CR_SPE_MAX_CYCLE_RESET 0x03E4

/* Register CR_IPE_SKIPPED_MV */
#define MVEA_CR_IPE_SKIPPED_MV      0x03EC
#define MASK_MVEA_CR_IPE_SKIPPED_MV_X 0x0000FF00
#define SHIFT_MVEA_CR_IPE_SKIPPED_MV_X 8
#define REGNUM_MVEA_CR_IPE_SKIPPED_MV_X 0x03EC

#define MASK_MVEA_CR_IPE_SKIPPED_MV_Y 0x000000FF
#define SHIFT_MVEA_CR_IPE_SKIPPED_MV_Y 0
#define REGNUM_MVEA_CR_IPE_SKIPPED_MV_Y 0x03EC


/* Table CR_JMCOMP_CHROMA_QUANTISER_TABLE */

/* Register CR_JMCOMP_CHROMA_QUANTISER */
#define MVEA_CR_JMCOMP_CHROMA_QUANTISER(X) (0x02D0 + (4 * (X)))
#define MASK_MVEA_CR_JMCOMP_CHROMA_QUANT(i) (0x000000FF << (0 + ((i) * 8)))
#define SHIFT_MVEA_CR_JMCOMP_CHROMA_QUANT(i) (0 + ((i) * 8))
#define REGNUM_MVEA_CR_JMCOMP_CHROMA_QUANT(X, i) (0x02D0 + (4 * (X)))

/* Number of entries in table CR_JMCOMP_CHROMA_QUANTISER_TABLE */

#define MVEA_CR_JMCOMP_CHROMA_QUANTISER_TABLE_SIZE_UINT32 16
#define MVEA_CR_JMCOMP_CHROMA_QUANTISER_TABLE_NUM_ENTRIES 16


/* Table CR_JMCOMP_LUMA_QUANTISER_TABLE */

/* Register CR_JMCOMP_LUMA_QUANTISER */
#define MVEA_CR_JMCOMP_LUMA_QUANTISER(X) (0x0290 + (4 * (X)))
#define MASK_MVEA_CR_JMCOMP_LUMA_QUANT(i) (0x000000FF << (0 + ((i) * 8)))
#define SHIFT_MVEA_CR_JMCOMP_LUMA_QUANT(i) (0 + ((i) * 8))
#define REGNUM_MVEA_CR_JMCOMP_LUMA_QUANT(X, i) (0x0290 + (4 * (X)))

/* Number of entries in table CR_JMCOMP_LUMA_QUANTISER_TABLE */

#define MVEA_CR_JMCOMP_LUMA_QUANTISER_TABLE_SIZE_UINT32 16
#define MVEA_CR_JMCOMP_LUMA_QUANTISER_TABLE_NUM_ENTRIES 16


/* Table CR_CMC_ESB_LOGICAL_REGION_SETUP_TABLE */

/* Register CR_CMC_ESB_LOGICAL_REGION_SETUP */
#define MVEA_CR_CMC_ESB_LOGICAL_REGION_SETUP(X) (0x0080 + (4 * (X)))
#define MASK_MVEA_CR_CMC_ESB_REGION_VALID 0x80000000
#define SHIFT_MVEA_CR_CMC_ESB_REGION_VALID 31
#define REGNUM_MVEA_CR_CMC_ESB_REGION_VALID 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_TYPE 0x60000000
#define SHIFT_MVEA_CR_CMC_ESB_REGION_TYPE 29
#define REGNUM_MVEA_CR_CMC_ESB_REGION_TYPE 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_LOGICAL_WIDTH 0x00F00000
#define SHIFT_MVEA_CR_CMC_ESB_REGION_LOGICAL_WIDTH 20
#define REGNUM_MVEA_CR_CMC_ESB_REGION_LOGICAL_WIDTH 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_LOGICAL_OFFSET_X 0x000F0000
#define SHIFT_MVEA_CR_CMC_ESB_REGION_LOGICAL_OFFSET_X 16
#define REGNUM_MVEA_CR_CMC_ESB_REGION_LOGICAL_OFFSET_X 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_PHYS_HEIGHT 0x0000F000
#define SHIFT_MVEA_CR_CMC_ESB_REGION_PHYS_HEIGHT 12
#define REGNUM_MVEA_CR_CMC_ESB_REGION_PHYS_HEIGHT 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_PHYS_WIDTH 0x00000F00
#define SHIFT_MVEA_CR_CMC_ESB_REGION_PHYS_WIDTH 8
#define REGNUM_MVEA_CR_CMC_ESB_REGION_PHYS_WIDTH 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_Y 0x000000F0
#define SHIFT_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_Y 4
#define REGNUM_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_Y 0x0080

#define MASK_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_X 0x0000000F
#define SHIFT_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_X 0
#define REGNUM_MVEA_CR_CMC_ESB_REGION_PHYS_ORIGIN_X 0x0080

/* **************** vlc register define **************** */

#define TOPAZ_VLC_CR_VLC_CONTROL    0x0000
#define MASK_TOPAZ_VLC_CR_CODEC     0x00000003
#define SHIFT_TOPAZ_VLC_CR_CODEC    0
#define REGNUM_TOPAZ_VLC_CR_CODEC   0x0000

#define MASK_TOPAZ_VLC_CR_SLICE_CODING_TYPE 0x0000000C
#define SHIFT_TOPAZ_VLC_CR_SLICE_CODING_TYPE 2
#define REGNUM_TOPAZ_VLC_CR_SLICE_CODING_TYPE 0x0000

#define MASK_TOPAZ_VLC_CR_START     0x00000010
#define SHIFT_TOPAZ_VLC_CR_START    4
#define REGNUM_TOPAZ_VLC_CR_START   0x0000

#define MASK_TOPAZ_VLC_CR_FLUSH     0x00000020
#define SHIFT_TOPAZ_VLC_CR_FLUSH    5
#define REGNUM_TOPAZ_VLC_CR_FLUSH   0x0000

#define MASK_TOPAZ_VLC_CR_FORCE_SKIP 0x00000040
#define SHIFT_TOPAZ_VLC_CR_FORCE_SKIP 6
#define REGNUM_TOPAZ_VLC_CR_FORCE_SKIP 0x0000

#define MASK_TOPAZ_VLC_CR_DISABLE_SKIP 0x00000080
#define SHIFT_TOPAZ_VLC_CR_DISABLE_SKIP 7
#define REGNUM_TOPAZ_VLC_CR_DISABLE_SKIP 0x0000

#define MASK_TOPAZ_VLC_CR_DISCARD_CODED_DATA 0x00004000
#define SHIFT_TOPAZ_VLC_CR_DISCARD_CODED_DATA 14
#define REGNUM_TOPAZ_VLC_CR_DISCARD_CODED_DATA 0x0000

/* Register CR_VLC_STATUS */
#define TOPAZ_VLC_CR_VLC_STATUS     0x0004
#define MASK_TOPAZ_VLC_CR_BUSY      0x00000001
#define SHIFT_TOPAZ_VLC_CR_BUSY     0
#define REGNUM_TOPAZ_VLC_CR_BUSY    0x0004

#define MASK_TOPAZ_VLC_CR_CODED_BUFFER_FULL 0x00000002
#define SHIFT_TOPAZ_VLC_CR_CODED_BUFFER_FULL 1
#define REGNUM_TOPAZ_VLC_CR_CODED_BUFFER_FULL 0x0004

#define MASK_TOPAZ_VLC_CR_RECODE_AS_IPCM 0x00000004
#define SHIFT_TOPAZ_VLC_CR_RECODE_AS_IPCM 2
#define REGNUM_TOPAZ_VLC_CR_RECODE_AS_IPCM 0x0004

/* Register CR_VLC_INFO_0 */
#define TOPAZ_VLC_CR_VLC_INFO_0     0x0008
#define MASK_TOPAZ_VLC_CR_CODED_WORDS_IN_MB 0x000000FF
#define SHIFT_TOPAZ_VLC_CR_CODED_WORDS_IN_MB 0
#define REGNUM_TOPAZ_VLC_CR_CODED_WORDS_IN_MB 0x0008

#define MASK_TOPAZ_VLC_CR_CODED_BLKS_IN_MB 0x00001F00
#define SHIFT_TOPAZ_VLC_CR_CODED_BLKS_IN_MB 8
#define REGNUM_TOPAZ_VLC_CR_CODED_BLKS_IN_MB 0x0008

#define MASK_TOPAZ_VLC_CR_FLUSH_STUFFING_BYTES 0x0003E000
#define SHIFT_TOPAZ_VLC_CR_FLUSH_STUFFING_BYTES 13
#define REGNUM_TOPAZ_VLC_CR_FLUSH_STUFFING_BYTES 0x0008

/* Register CR_VLC_INFO_1 */
#define TOPAZ_VLC_CR_VLC_INFO_1     0x000C
#define MASK_TOPAZ_VLC_CR_SKIPPED_MBS_IN_FRAME 0x00000FFF
#define SHIFT_TOPAZ_VLC_CR_SKIPPED_MBS_IN_FRAME 0
#define REGNUM_TOPAZ_VLC_CR_SKIPPED_MBS_IN_FRAME 0x000C

#define MASK_TOPAZ_VLC_CR_CODED_MBS_IN_FRAME 0x00FFF000
#define SHIFT_TOPAZ_VLC_CR_CODED_MBS_IN_FRAME 12
#define REGNUM_TOPAZ_VLC_CR_CODED_MBS_IN_FRAME 0x000C

/* Register CR_VLC_INFO_2 */
#define TOPAZ_VLC_CR_VLC_INFO_2     0x0010
#define MASK_TOPAZ_VLC_CR_INTRA_MBS_IN_FRAME 0x00000FFF
#define SHIFT_TOPAZ_VLC_CR_INTRA_MBS_IN_FRAME 0
#define REGNUM_TOPAZ_VLC_CR_INTRA_MBS_IN_FRAME 0x0010

#define MASK_TOPAZ_VLC_CR_INTER_MBS_IN_FRAME 0x00FFF000
#define SHIFT_TOPAZ_VLC_CR_INTER_MBS_IN_FRAME 12
#define REGNUM_TOPAZ_VLC_CR_INTER_MBS_IN_FRAME 0x0010

/* Register CR_VLC_STUFF_HEAD_CTRL */
#define TOPAZ_VLC_CR_VLC_STUFF_HEAD_CTRL 0x0014
#define MASK_TOPAZ_VLC_CR_HEADER_ELEMENTS 0x0000001F
#define SHIFT_TOPAZ_VLC_CR_HEADER_ELEMENTS 0
#define REGNUM_TOPAZ_VLC_CR_HEADER_ELEMENTS 0x0014

#define MASK_TOPAZ_VLC_CR_STUFFING_WORDS 0x00003FE0
#define SHIFT_TOPAZ_VLC_CR_STUFFING_WORDS 5
#define REGNUM_TOPAZ_VLC_CR_STUFFING_WORDS 0x0014

/* Register CR_VLC_HEADER_FIFO */
#define TOPAZ_VLC_CR_VLC_HEADER_FIFO 0x0018
#define MASK_TOPAZ_VLC_CR_HEADER_DATA 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_HEADER_DATA 0
#define REGNUM_TOPAZ_VLC_CR_HEADER_DATA 0x0018

/* Register CR_VLC_HEADER_CTRL */
#define TOPAZ_VLC_CR_VLC_HEADER_CTRL 0x001C
#define MASK_TOPAZ_VLC_CR_HEADER_PREFIX 0x7FFFFFFF
#define SHIFT_TOPAZ_VLC_CR_HEADER_PREFIX 0
#define REGNUM_TOPAZ_VLC_CR_HEADER_PREFIX 0x001C

#define MASK_TOPAZ_VLC_CR_DISABLE_PREFIX_DETECTION 0x80000000
#define SHIFT_TOPAZ_VLC_CR_DISABLE_PREFIX_DETECTION 31
#define REGNUM_TOPAZ_VLC_CR_DISABLE_PREFIX_DETECTION 0x001C

/* Register CR_VLC_HEADER_STATUS */
#define TOPAZ_VLC_CR_VLC_HEADER_STATUS 0x0020
#define MASK_TOPAZ_VLC_CR_HEADER_FIFO_FULL 0x00000001
#define SHIFT_TOPAZ_VLC_CR_HEADER_FIFO_FULL 0
#define REGNUM_TOPAZ_VLC_CR_HEADER_FIFO_FULL 0x0020

/* Register CR_VLC_RATE_CTRL_0 */
#define TOPAZ_VLC_CR_VLC_RATE_CTRL_0 0x0024
#define MASK_TOPAZ_VLC_CR_MV_BITS   0x0000FFFF
#define SHIFT_TOPAZ_VLC_CR_MV_BITS  0
#define REGNUM_TOPAZ_VLC_CR_MV_BITS 0x0024

#define MASK_TOPAZ_VLC_CR_DC_BITS   0x00FF0000
#define SHIFT_TOPAZ_VLC_CR_DC_BITS  16
#define REGNUM_TOPAZ_VLC_CR_DC_BITS 0x0024

#define MASK_TOPAZ_VLC_CR_MB_CODING_TYPE 0x03000000
#define SHIFT_TOPAZ_VLC_CR_MB_CODING_TYPE 24
#define REGNUM_TOPAZ_VLC_CR_MB_CODING_TYPE 0x0024

/* Register CR_VLC_RATE_CTRL_1 */
#define TOPAZ_VLC_CR_VLC_RATE_CTRL_1 0x002C
#define MASK_TOPAZ_VLC_CR_MB_RESIDUAL_BITS 0x0000FFFF
#define SHIFT_TOPAZ_VLC_CR_MB_RESIDUAL_BITS 0
#define REGNUM_TOPAZ_VLC_CR_MB_RESIDUAL_BITS 0x002C

#define MASK_TOPAZ_VLC_CR_MB_SYMBOLS_BITS 0xFFFF0000
#define SHIFT_TOPAZ_VLC_CR_MB_SYMBOLS_BITS 16
#define REGNUM_TOPAZ_VLC_CR_MB_SYMBOLS_BITS 0x002C

/* Register CR_VLC_BUFFER_SIZE */
#define TOPAZ_VLC_CR_VLC_BUFFER_SIZE 0x0034
#define MASK_TOPAZ_VLC_CR_CODED_BUFFER_SIZE_WORDS 0x000000FF
#define SHIFT_TOPAZ_VLC_CR_CODED_BUFFER_SIZE_WORDS 0
#define REGNUM_TOPAZ_VLC_CR_CODED_BUFFER_SIZE_WORDS 0x0034

/* Register CR_VLC_SIGNATURE_0 */
#define TOPAZ_VLC_CR_VLC_SIGNATURE_0 0x0038
#define MASK_TOPAZ_VLC_CR_MB_SIGNATURE 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_MB_SIGNATURE 0
#define REGNUM_TOPAZ_VLC_CR_MB_SIGNATURE 0x0038

/* Register CR_VLC_SIGNATURE_1 */
#define TOPAZ_VLC_CR_VLC_SIGNATURE_1 0x003C
#define MASK_TOPAZ_VLC_CR_BLK_SIGNATURE 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_BLK_SIGNATURE 0
#define REGNUM_TOPAZ_VLC_CR_BLK_SIGNATURE 0x003C

/* Register CR_VLC_SIGNATURE_2 */
#define TOPAZ_VLC_CR_VLC_SIGNATURE_2 0x0040
#define MASK_TOPAZ_VLC_CR_LOOKUP_SIGNATURE 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_LOOKUP_SIGNATURE 0
#define REGNUM_TOPAZ_VLC_CR_LOOKUP_SIGNATURE 0x0040

/* Register CR_VLC_SIGNATURE_3 */
#define TOPAZ_VLC_CR_VLC_SIGNATURE_3 0x0044
#define MASK_TOPAZ_VLC_CR_BITSTREAM_SIGNATURE 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_BITSTREAM_SIGNATURE 0
#define REGNUM_TOPAZ_VLC_CR_BITSTREAM_SIGNATURE 0x0044

/* Register CR_VLC_SIGNATURE_4 */
#define TOPAZ_VLC_CR_VLC_SIGNATURE_4 0x0048
#define MASK_TOPAZ_VLC_CR_HEADER_SIGNATURE 0xFFFFFFFF
#define SHIFT_TOPAZ_VLC_CR_HEADER_SIGNATURE 0
#define REGNUM_TOPAZ_VLC_CR_HEADER_SIGNATURE 0x0048

/* Register CR_VLC_JPEG_CFG */
#define TOPAZ_VLC_CR_VLC_JPEG_CFG   0x004C
#define MASK_TOPAZ_VLC_CR_JPEG_BLKS_IN_UNIT_MINUS_1 0x00000007
#define SHIFT_TOPAZ_VLC_CR_JPEG_BLKS_IN_UNIT_MINUS_1 0
#define REGNUM_TOPAZ_VLC_CR_JPEG_BLKS_IN_UNIT_MINUS_1 0x004C

#define MASK_TOPAZ_VLC_CR_JPEG_CHROMA_BLK_SELECT 0x0000FF00
#define SHIFT_TOPAZ_VLC_CR_JPEG_CHROMA_BLK_SELECT 8
#define REGNUM_TOPAZ_VLC_CR_JPEG_CHROMA_BLK_SELECT 0x004C

/* Register CR_VLC_PERFORMANCE_0 */
#define TOPAZ_VLC_CR_VLC_PERFORMANCE_0 0x0050
#define MASK_TOPAZ_VLC_CR_WORST_MB_CYCLES 0x0000FFFF
#define SHIFT_TOPAZ_VLC_CR_WORST_MB_CYCLES 0
#define REGNUM_TOPAZ_VLC_CR_WORST_MB_CYCLES 0x0050

#define MASK_TOPAZ_VLC_CR_WORST_MB_TYPE 0x00030000
#define SHIFT_TOPAZ_VLC_CR_WORST_MB_TYPE 16
#define REGNUM_TOPAZ_VLC_CR_WORST_MB_TYPE 0x0050

/* Register CR_VLC_PERFORMANCE_1 */
#define TOPAZ_VLC_CR_VLC_PERFORMANCE_1 0x0054
#define MASK_TOPAZ_VLC_CR_WORST_MB_NUM 0x003FFFFF
#define SHIFT_TOPAZ_VLC_CR_WORST_MB_NUM 0
#define REGNUM_TOPAZ_VLC_CR_WORST_MB_NUM 0x0054

/* Register CR_VLC_PERFORMANCE_2 */
#define TOPAZ_VLC_CR_VLC_PERFORMANCE_2 0x0058
#define MASK_TOPAZ_VLC_CR_WORST_MB_RESET 0x00000001
#define SHIFT_TOPAZ_VLC_CR_WORST_MB_RESET 0
#define REGNUM_TOPAZ_VLC_CR_WORST_MB_RESET 0x0058

#define MASK_TOPAZ_VLC_CR_DISABLE_COUNTERS 0x00000002
#define SHIFT_TOPAZ_VLC_CR_DISABLE_COUNTERS 1
#define REGNUM_TOPAZ_VLC_CR_DISABLE_COUNTERS 0x0058

/* Register CR_VLC_IPCM_0 */
#define TOPAZ_VLC_CR_VLC_IPCM_0     0x005C
#define MASK_TOPAZ_VLC_CR_MB_TYPE_POSITION 0x000003FF
#define SHIFT_TOPAZ_VLC_CR_MB_TYPE_POSITION 0
#define REGNUM_TOPAZ_VLC_CR_MB_TYPE_POSITION 0x005C

/* Register CR_VLC_IPCM_1 */
#define TOPAZ_VLC_CR_VLC_IPCM_1     0x0060
#define MASK_TOPAZ_VLC_CR_IPCM_THRESHOLD 0x00000FFF
#define SHIFT_TOPAZ_VLC_CR_IPCM_THRESHOLD 0
#define REGNUM_TOPAZ_VLC_CR_IPCM_THRESHOLD 0x0060

/* Register CR_VLC_MPEG4_CFG */
#define TOPAZ_VLC_CR_VLC_MPEG4_CFG  0x0064
#define MASK_TOPAZ_VLC_CR_RSIZE     0x00000007
#define SHIFT_TOPAZ_VLC_CR_RSIZE    0
#define REGNUM_TOPAZ_VLC_CR_RSIZE   0x0064

/* Register CR_VLC_MB_PARAMS */
#define TOPAZ_VLC_CR_VLC_MB_PARAMS  0x0068
#define MASK_TOPAZ_VLC_CR_QP        0x0000003F
#define SHIFT_TOPAZ_VLC_CR_QP       0
#define REGNUM_TOPAZ_VLC_CR_QP      0x0068

#define MASK_TOPAZ_VLC_CR_CBP       0x00000FC0
#define SHIFT_TOPAZ_VLC_CR_CBP      6
#define REGNUM_TOPAZ_VLC_CR_CBP     0x0068

/* Register CR_VLC_RESET */
#define TOPAZ_VLC_CR_VLC_RESET      0x006C
#define MASK_TOPAZ_VLC_CR_RESET     0x00000001
#define SHIFT_TOPAZ_VLC_CR_RESET    0
#define REGNUM_TOPAZ_VLC_CR_RESET   0x006C

/* **************** topaz register define **************** */

#define TOPAZ_CR_IMG_TOPAZ_SRST     0x0000
#define MASK_TOPAZ_CR_IMG_TOPAZ_MVEA_SOFT_RESET 0x00000001
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MVEA_SOFT_RESET 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MVEA_SOFT_RESET 0x0000

#define MASK_TOPAZ_CR_IMG_TOPAZ_MTX_SOFT_RESET 0x00000002
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MTX_SOFT_RESET 1
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MTX_SOFT_RESET 0x0000

#define MASK_TOPAZ_CR_IMG_TOPAZ_IO_SOFT_RESET 0x00000004
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_IO_SOFT_RESET 2
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_IO_SOFT_RESET 0x0000

#define MASK_TOPAZ_CR_IMG_TOPAZ_VLC_SOFT_RESET 0x00000008
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_VLC_SOFT_RESET 3
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_VLC_SOFT_RESET 0x0000

#define MASK_TOPAZ_CR_IMG_TOPAZ_DB_SOFT_RESET 0x00000010
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_DB_SOFT_RESET 4
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_DB_SOFT_RESET 0x0000

/* Register CR_IMG_TOPAZ_INTSTAT */
#define TOPAZ_CR_IMG_TOPAZ_INTSTAT  0x0004
#define MASK_TOPAZ_CR_IMG_TOPAZ_INTS_MVEA 0x00000001
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTS_MVEA 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTS_MVEA 0x0004

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTS_MTX 0x00000002
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTS_MTX 1
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTS_MTX 0x0004

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTS_MTX_HALT 0x00000004
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTS_MTX_HALT 2
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTS_MTX_HALT 0x0004

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTS_MMU_FAULT 0x00000008
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTS_MMU_FAULT 3
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTS_MMU_FAULT 0x0004

#define MASK_TOPAZ_CR_IMG_TOPAZ_MAS_INTS 0x80000000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MAS_INTS 31
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MAS_INTS 0x0004

/* Register CR_IMG_TOPAZ_INTENAB */
#define TOPAZ_CR_IMG_TOPAZ_INTENAB  0x0008
#define MASK_TOPAZ_CR_IMG_TOPAZ_INTEN_MVEA 0x00000001
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTEN_MVEA 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTEN_MVEA 0x0008

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX 0x00000002
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX 1
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX 0x0008

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX_HALT 0x00000004
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX_HALT 2
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTEN_MTX_HALT 0x0008

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTEN_MMU_FAULT 0x00000008
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTEN_MMU_FAULT 3
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTEN_MMU_FAULT 0x0008

#define MASK_TOPAZ_CR_IMG_TOPAZ_MAS_INTEN 0x80000000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MAS_INTEN 31
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MAS_INTEN 0x0008

/* Register CR_IMG_TOPAZ_INTCLEAR */
#define TOPAZ_CR_IMG_TOPAZ_INTCLEAR 0x000C
#define MASK_TOPAZ_CR_IMG_TOPAZ_INTCLR_MVEA 0x00000001
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTCLR_MVEA 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTCLR_MVEA 0x000C

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX 0x00000002
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX 1
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX 0x000C

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX_HALT 0x00000004
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX_HALT 2
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX_HALT 0x000C

#define MASK_TOPAZ_CR_IMG_TOPAZ_INTCLR_MMU_FAULT 0x00000008
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_INTCLR_MMU_FAULT 3
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_INTCLR_MMU_FAULT 0x000C

/* Register CR_TOPAZ_MAN_CLK_GATE */
#define TOPAZ_CR_TOPAZ_MAN_CLK_GATE 0x0010
#define MASK_TOPAZ_CR_TOPAZ_MVEA_MAN_CLK_GATE 0x00000001
#define SHIFT_TOPAZ_CR_TOPAZ_MVEA_MAN_CLK_GATE 0
#define REGNUM_TOPAZ_CR_TOPAZ_MVEA_MAN_CLK_GATE 0x0010

#define MASK_TOPAZ_CR_TOPAZ_MTX_MAN_CLK_GATE 0x00000002
#define SHIFT_TOPAZ_CR_TOPAZ_MTX_MAN_CLK_GATE 1
#define REGNUM_TOPAZ_CR_TOPAZ_MTX_MAN_CLK_GATE 0x0010

#define MASK_TOPAZ_CR_TOPAZ_VLC_MAN_CLK_GATE 0x00000004
#define SHIFT_TOPAZ_CR_TOPAZ_VLC_MAN_CLK_GATE 2
#define REGNUM_TOPAZ_CR_TOPAZ_VLC_MAN_CLK_GATE 0x0010

#define MASK_TOPAZ_CR_TOPAZ_DB_MAN_CLK_GATE 0x00000008
#define SHIFT_TOPAZ_CR_TOPAZ_DB_MAN_CLK_GATE 3
#define REGNUM_TOPAZ_CR_TOPAZ_DB_MAN_CLK_GATE 0x0010

/* Register CR_TOPAZ_AUTO_CLK_GATE */
#define TOPAZ_CR_TOPAZ_AUTO_CLK_GATE 0x0014
#define MASK_TOPAZ_CR_TOPAZ_VLC_AUTO_CLK_GATE 0x00000001
#define SHIFT_TOPAZ_CR_TOPAZ_VLC_AUTO_CLK_GATE 0
#define REGNUM_TOPAZ_CR_TOPAZ_VLC_AUTO_CLK_GATE 0x0014

#define MASK_TOPAZ_CR_TOPAZ_DB_AUTO_CLK_GATE 0x00000002
#define SHIFT_TOPAZ_CR_TOPAZ_DB_AUTO_CLK_GATE 1
#define REGNUM_TOPAZ_CR_TOPAZ_DB_AUTO_CLK_GATE 0x0014

/* Register CR_TOPAZ_MTX_C_RATIO */
#define TOPAZ_CR_TOPAZ_MTX_C_RATIO  0x0018
#define MASK_TOPAZ_MTX_C_RATIO      0x00000003
#define SHIFT_TOPAZ_MTX_C_RATIO     0
#define REGNUM_TOPAZ_MTX_C_RATIO    0x0018

/* Register CR_MMU_STATUS */
#define TOPAZ_CR_MMU_STATUS         0x001C
#define MASK_TOPAZ_CR_MMU_PF_N_RW   0x00000001
#define SHIFT_TOPAZ_CR_MMU_PF_N_RW  0
#define REGNUM_TOPAZ_CR_MMU_PF_N_RW 0x001C

#define MASK_TOPAZ_CR_MMU_FAULT_ADDR 0xFFFFF000
#define SHIFT_TOPAZ_CR_MMU_FAULT_ADDR 12
#define REGNUM_TOPAZ_CR_MMU_FAULT_ADDR 0x001C

/* Register CR_MMU_MEM_REQ */
#define TOPAZ_CR_MMU_MEM_REQ        0x0020
#define MASK_TOPAZ_CR_MEM_REQ_STAT_READS 0x000000FF
#define SHIFT_TOPAZ_CR_MEM_REQ_STAT_READS 0
#define REGNUM_TOPAZ_CR_MEM_REQ_STAT_READS 0x0020

/* Register CR_MMU_CONTROL0 */
#define TOPAZ_CR_MMU_CONTROL0       0x0024
#define MASK_TOPAZ_CR_MMU_BYPASS    0x00000800
#define SHIFT_TOPAZ_CR_MMU_BYPASS   11
#define REGNUM_TOPAZ_CR_MMU_BYPASS  0x0024

#define MASK_TOPAZ_CR_FLOWRATE_CMC  0x00000700
#define SHIFT_TOPAZ_CR_FLOWRATE_CMC 8
#define REGNUM_TOPAZ_CR_FLOWRATE_CMC 0x0024

#define MASK_TOPAZ_CR_MMU_NOREORDER 0x00000001
#define SHIFT_TOPAZ_CR_MMU_NOREORDER 0
#define REGNUM_TOPAZ_CR_MMU_NOREORDER 0x0024

#define MASK_TOPAZ_CR_MMU_PAUSE     0x00000002
#define SHIFT_TOPAZ_CR_MMU_PAUSE    1
#define REGNUM_TOPAZ_CR_MMU_PAUSE   0x0024

#define MASK_TOPAZ_CR_MMU_FLUSH     0x00000004
#define SHIFT_TOPAZ_CR_MMU_FLUSH    2
#define REGNUM_TOPAZ_CR_MMU_FLUSH   0x0024

#define MASK_TOPAZ_CR_MMU_INVALDC   0x00000008
#define SHIFT_TOPAZ_CR_MMU_INVALDC  3
#define REGNUM_TOPAZ_CR_MMU_INVALDC 0x0024

/* Register CR_MMU_CONTROL1 */
#define TOPAZ_CR_MMU_CONTROL1       0x0028
#define MASK_TOPAZ_CR_MMU_PAGE_SIZE 0xF0000000
#define SHIFT_TOPAZ_CR_MMU_PAGE_SIZE 28
#define REGNUM_TOPAZ_CR_MMU_PAGE_SIZE 0x0028

#define MASK_TOPAZ_CR_MMU_BEST_COUNT 0x0FF00000
#define SHIFT_TOPAZ_CR_MMU_BEST_COUNT 20
#define REGNUM_TOPAZ_CR_MMU_BEST_COUNT 0x0028

#define MASK_TOPAZ_CR_MMU_ADT_TTE   0x000FF000
#define SHIFT_TOPAZ_CR_MMU_ADT_TTE  12
#define REGNUM_TOPAZ_CR_MMU_ADT_TTE 0x0028

#define MASK_TOPAZ_CR_MMU_TTE_THRESHOLD 0x00000FFF
#define SHIFT_TOPAZ_CR_MMU_TTE_THRESHOLD 0
#define REGNUM_TOPAZ_CR_MMU_TTE_THRESHOLD 0x0028

/* Register CR_MMU_BANK_INDEX */
#define TOPAZ_CR_MMU_BANK_INDEX     0x0038
#define MASK_TOPAZ_CR_MMU_BANK_N_INDEX_M(i) (0x00000003 << (8 + ((i) * 2)))
#define SHIFT_TOPAZ_CR_MMU_BANK_N_INDEX_M(i) (8 + ((i) * 2))
#define REGNUM_TOPAZ_CR_MMU_BANK_N_INDEX_M(i) 0x0038

#define MASK_TOPAZ_CR_MMU_BANK_SELECT(i) (0x00000001 << (0 + ((i) * 1)))
#define SHIFT_TOPAZ_CR_MMU_BANK_SELECT(i) (0 + ((i) * 1))
#define REGNUM_TOPAZ_CR_MMU_BANK_SELECT(i) 0x0038

/* Register CR_MTX_DEBUG */
#define TOPAZ_CR_MTX_DEBUG          0x003C
#define MASK_TOPAZ_CR_MTX_DBG_GPIO_IN 0x00000003
#define SHIFT_TOPAZ_CR_MTX_DBG_GPIO_IN 0
#define REGNUM_TOPAZ_CR_MTX_DBG_GPIO_IN 0x003C

#define MASK_TOPAZ_CR_MTX_DBG_IS_SLAVE 0x00000004
#define SHIFT_TOPAZ_CR_MTX_DBG_IS_SLAVE 2
#define REGNUM_TOPAZ_CR_MTX_DBG_IS_SLAVE 0x003C

#define MASK_TOPAZ_CR_MTX_DBG_GPIO_OUT 0x00000018
#define SHIFT_TOPAZ_CR_MTX_DBG_GPIO_OUT 3
#define REGNUM_TOPAZ_CR_MTX_DBG_GPIO_OUT 0x003C

#define MASK_TOPAZ_CR_MTX_RAM_BANKS 0x00000F00
#define SHIFT_TOPAZ_CR_MTX_RAM_BANKS 8
#define REGNUM_TOPAZ_CR_MTX_RAM_BANKS 0x003C

#define MASK_TOPAZ_CR_MTX_RAM_BANK_SIZE 0x000F0000
#define SHIFT_TOPAZ_CR_MTX_RAM_BANK_SIZE 16
#define REGNUM_TOPAZ_CR_MTX_RAM_BANK_SIZE 0x003C

#define MASK_TOPAZ_CR_MTX_LAST_RAM_BANK_SIZE 0x0F000000
#define SHIFT_TOPAZ_CR_MTX_LAST_RAM_BANK_SIZE 24
#define REGNUM_TOPAZ_CR_MTX_LAST_RAM_BANK_SIZE 0x003C

/* Register CR_IMG_TOPAZ_DMAC_MODE */
#define TOPAZ_CR_IMG_TOPAZ_DMAC_MODE 0x0040
#define MASK_TOPAZ_CR_DMAC_MASTER_MODE 0x00000001
#define SHIFT_TOPAZ_CR_DMAC_MASTER_MODE 0
#define REGNUM_TOPAZ_CR_DMAC_MASTER_MODE 0x0040

/* Register CR_IMG_TOPAZ_RSVD0 */
#define TOPAZ_CR_IMG_TOPAZ_RSVD0    0x03B0
#define MASK_TOPAZ_CR_IMG_TOPAZ_RESERVED0 0xFFFFFFFF
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_RESERVED0 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_RESERVED0 0x03B0

/* Register CR_IMG_TOPAZ_CORE_ID */
#define TOPAZ_CR_IMG_TOPAZ_CORE_ID  0x03C0
#define MASK_TOPAZ_CR_IMG_TOPAZ_CORE_CONFIG 0x0000FFFF
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_CORE_CONFIG 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_CORE_CONFIG 0x03C0

#define MASK_TOPAZ_CR_IMG_TOPAZ_CORE_ID 0x00FF0000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_CORE_ID 16
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_CORE_ID 0x03C0

#define MASK_TOPAZ_CR_IMG_TOPAZ_GROUP_ID 0xFF000000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_GROUP_ID 24
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_GROUP_ID 0x03C0

/* Register CR_IMG_TOPAZ_CORE_REV */
#define TOPAZ_CR_IMG_TOPAZ_CORE_REV 0x03D0
#define MASK_TOPAZ_CR_IMG_TOPAZ_MAINT_REV 0x000000FF
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MAINT_REV 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MAINT_REV 0x03D0

#define MASK_TOPAZ_CR_IMG_TOPAZ_MINOR_REV 0x0000FF00
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MINOR_REV 8
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MINOR_REV 0x03D0

#define MASK_TOPAZ_CR_IMG_TOPAZ_MAJOR_REV 0x00FF0000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_MAJOR_REV 16
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_MAJOR_REV 0x03D0

#define MASK_TOPAZ_CR_IMG_TOPAZ_DESIGNER 0xFF000000
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_DESIGNER 24
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_DESIGNER 0x03D0

/* Register CR_IMG_TOPAZ_CORE_DES1 */
#define TOPAZ_CR_IMG_TOPAZ_CORE_DES1 0x03E0
#define MASK_TOPAZ_CR_IMG_TOPAZ_DESIGNER1 0xFFFFFFFF
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_DESIGNER1 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_DESIGNER1 0x03E0

/* Register CR_IMG_TOPAZ_CORE_DES2 */
#define TOPAZ_CR_IMG_TOPAZ_CORE_DES2 0x03F0
#define MASK_TOPAZ_CR_IMG_TOPAZ_DESIGNER2 0xFFFFFFFF
#define SHIFT_TOPAZ_CR_IMG_TOPAZ_DESIGNER2 0
#define REGNUM_TOPAZ_CR_IMG_TOPAZ_DESIGNER2 0x03F0


/* Table MMU_TILE */

/* Register CR_MMU_TILE */
#define TOPAZ_CR_MMU_TILE(X)        (0x0034 + (4 * (X)))
#define MASK_TOPAZ_CR_TILE_CFG      0x0F000000
#define SHIFT_TOPAZ_CR_TILE_CFG     24
#define REGNUM_TOPAZ_CR_TILE_CFG    0x0034

#define MASK_TOPAZ_CR_TILE_MAX_ADDR 0x00FFF000
#define SHIFT_TOPAZ_CR_TILE_MAX_ADDR 12
#define REGNUM_TOPAZ_CR_TILE_MAX_ADDR 0x0034

#define MASK_TOPAZ_CR_TILE_MIN_ADDR 0x00000FFF
#define SHIFT_TOPAZ_CR_TILE_MIN_ADDR 0
#define REGNUM_TOPAZ_CR_TILE_MIN_ADDR 0x0034

/* Number of entries in table MMU_TILE */

#define TOPAZ_MMU_TILE_SIZE_UINT32  1
#define TOPAZ_MMU_TILE_NUM_ENTRIES  1


/* Table MMU_DIR_LIST_BASE */

/* Register CR_MMU_DIR_LIST_BASE */
#define TOPAZ_CR_MMU_DIR_LIST_BASE(X) (0x0030 + (4 * (X)))
#define MASK_TOPAZ_CR_MMU_DIR_LIST_BASE_ADDR 0xFFFFF000
#define SHIFT_TOPAZ_CR_MMU_DIR_LIST_BASE_ADDR 12
#define REGNUM_TOPAZ_CR_MMU_DIR_LIST_BASE_ADDR 0x0030

/* Number of entries in table MMU_DIR_LIST_BASE */

#define TOPAZ_MMU_DIR_LIST_BASE_SIZE_UINT32 1
#define TOPAZ_MMU_DIR_LIST_BASE_NUM_ENTRIES 1

/* **************** mtx core registers define **************** */

#define	MTX_CORE_CR_MTX_RAM_ACCESS_DATA_TRANSFER_OFFSET	0x00000104

#define	MTX_CORE_CR_MTX_RAM_ACCESS_STATUS_OFFSET 0x0000010C
#define	MTX_CORE_CR_MTX_RAM_ACCESS_STATUS_MTX_MTX_MCM_STAT_MASK	0x00000001

#define	TOPAZ_CORE_CR_MTX_DEBUG_OFFSET	0x0000003C
#define TOPAZ_CORE_CR_MTX_DEBUG_CR_MTX_DBG_IS_SLAVE_MASK	0x00000004
#define TOPAZ_CORE_CR_MTX_DEBUG_CR_MTX_DBG_IS_SLAVE_SHIFT	0x00000002
#define TOPAZ_CORE_CR_MTX_DEBUG_CR_MTX_DBG_GPIO_IN_MASK		0x00000003
#define TOPAZ_CORE_CR_MTX_DEBUG_CR_MTX_DBG_GPIO_IN_SHIFT	0x00000000

#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_OFFSET		0x00000108
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCMAI_MASK	0x00000002
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCMAI_SHIFT	0x00000001
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCMID_MASK	0x0FF00000
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCMID_SHIFT	0x00000014
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCM_ADDR_MASK	0x000FFFFC
#define	MTX_CORE_CR_MTX_RAM_ACCESS_CONTROL_MTX_MCM_ADDR_SHIFT	0x00000002

#define	MTX_CORE_CR_MTX_SOFT_RESET_OFFSET			0x00000200
#define	MTX_CORE_CR_MTX_SOFT_RESET_MTX_RESET_MASK		0x00000001

#define	MTX_CORE_CR_MTX_REGISTER_READ_WRITE_DATA_OFFSET		0x000000F8

/* test */
#define MTX_CORE_CR_MTX_SYSC_CDMAA_OFFSET                       0x00000344
#define MTX_CORE_CR_MTX_SYSC_CDMAC_OFFSET                       0x00000340


#define	MTX_CORE_CR_MTX_REGISTER_READ_WRITE_REQUEST_OFFSET	0x000000FC
#define	MTX_CORE_CR_MTX_REGISTER_READ_WRITE_REQUEST_MTX_RNW_MASK 0x00010000
#define	MTX_CORE_CR_MTX_REGISTER_READ_WRITE_REQUEST_MTX_DREADY_MASK 0x80000000

#define		MTX_CORE_CR_MTX_ENABLE_OFFSET		0x00000000
#define		MTX_CORE_CR_MTX_ENABLE_MTX_ENABLE_MASK	0x00000001
#define		MTX_CORE_CR_MTX_ENABLE_MTX_TOFF_MASK	0x00000002
#define		MTX_CORE_CR_MTX_ENABLE_MTX_TSTOPPED_MASK	0x00000004

#define		MTX_MEMORY_BASE		(0x80900000)
#define		PC_START_ADDRESS	(0x80900000)

#if 1
#define		LNC_MTX_CORE_CODE_MEM	(0x10)
#define		LNC_MTX_CORE_DATA_MEM	(0x18)
#endif

#define		TOPAZ_MTX_PC		(0x00000005)


#define MTX_DATA_MEM_BASE		0x82880000

/* **************** DMAC register define **************** */

#define IMG_SOC_DMAC_SOFT_RESET     0x0080

/* Table DMAC */

/* Register DMAC_PER_HOLD */
#define IMG_SOC_DMAC_PER_HOLD(X)    (0x0018 + (32 * (X)))
#define MASK_IMG_SOC_PER_HOLD       0x0000007F
#define SHIFT_IMG_SOC_PER_HOLD      0
#define REGNUM_IMG_SOC_PER_HOLD     0x0018

/* Register DMAC_PERIPHERAL_ADDR */
#define IMG_SOC_DMAC_PERIPHERAL_ADDR(X) (0x0014 + (32 * (X)))
#define MASK_IMG_SOC_ADDR           0x007FFFFF
#define SHIFT_IMG_SOC_ADDR          0
#define REGNUM_IMG_SOC_ADDR         0x0014

/* Register DMAC_2D_MODE */
#define IMG_SOC_DMAC_2D_MODE(X)     (0x0010 + (32 * (X)))
#define MASK_IMG_SOC_ROW_LENGTH     0x000003FF
#define SHIFT_IMG_SOC_ROW_LENGTH    0
#define REGNUM_IMG_SOC_ROW_LENGTH   0x0010

#define MASK_IMG_SOC_LINE_ADDR_OFFSET 0x000FFC00
#define SHIFT_IMG_SOC_LINE_ADDR_OFFSET 10
#define REGNUM_IMG_SOC_LINE_ADDR_OFFSET 0x0010

#define MASK_IMG_SOC_REP_COUNT      0x7FF00000
#define SHIFT_IMG_SOC_REP_COUNT     20
#define REGNUM_IMG_SOC_REP_COUNT    0x0010

/* Register DMAC_IRQ_STAT */
#define IMG_SOC_DMAC_IRQ_STAT(X)    (0x000C + (32 * (X)))
#define MASK_IMG_SOC_TRANSFER_FIN   0x00020000
#define SHIFT_IMG_SOC_TRANSFER_FIN  17
#define REGNUM_IMG_SOC_TRANSFER_FIN 0x000C

#define MASK_IMG_SOC_LIST_INT       0x00100000
#define SHIFT_IMG_SOC_LIST_INT      20
#define REGNUM_IMG_SOC_LIST_INT     0x000C
/* The last linked-list element processed initiated an interrupt.
 * If LIST_IEN is set for the channel, an interrupt will be generated
 * on the IRQ line until this bit is cleared,
*/
#define IMG_SOC_LIST_INT_ENABLE	    0x00000001

/* last linked list element processed did not initiate an interrupt. */
#define IMG_SOC_LIST_INT_DISABLE    0x00000000

#define MASK_IMG_SOC_LIST_FIN       0x00200000
#define SHIFT_IMG_SOC_LIST_FIN      21
#define REGNUM_IMG_SOC_LIST_FIN     0x000C

/* Register DMAC_PERIPH */
#define IMG_SOC_DMAC_PERIPH(X)      (0x0008 + (32 * (X)))
#define MASK_IMG_SOC_EXT_SA         0x0000000F
#define SHIFT_IMG_SOC_EXT_SA        0
#define REGNUM_IMG_SOC_EXT_SA       0x0008

#define MASK_IMG_SOC_BURST          0x07000000
#define SHIFT_IMG_SOC_BURST         24
#define REGNUM_IMG_SOC_BURST        0x0008

#define MASK_IMG_SOC_INCR           0x08000000
#define SHIFT_IMG_SOC_INCR          27
#define REGNUM_IMG_SOC_INCR         0x0008

#define MASK_IMG_SOC_ACC_DEL        0xE0000000
#define SHIFT_IMG_SOC_ACC_DEL       29
#define REGNUM_IMG_SOC_ACC_DEL      0x0008

/* Register DMAC_COUNT */
#define IMG_SOC_DMAC_COUNT(X)       (0x0004 + (32 * (X)))
#define MASK_IMG_SOC_CNT            0x0000FFFF
#define SHIFT_IMG_SOC_CNT           0
#define REGNUM_IMG_SOC_CNT          0x0004

#define MASK_IMG_SOC_EN             0x00010000
#define SHIFT_IMG_SOC_EN            16
#define REGNUM_IMG_SOC_EN           0x0004

#define MASK_IMG_SOC_ENABLE_2D_MODE 0x00020000
#define SHIFT_IMG_SOC_ENABLE_2D_MODE 17
#define REGNUM_IMG_SOC_ENABLE_2D_MODE 0x0004
#define IMG_SOC_ENABLE_2D_MODE_ENABLED		0x00000001
#define IMG_SOC_ENABLE_2D_MODE_DISABLED		0x00000000

#define MASK_IMG_SOC_LIST_EN        0x00040000
#define SHIFT_IMG_SOC_LIST_EN       18
#define REGNUM_IMG_SOC_LIST_EN      0x0004

#define MASK_IMG_SOC_SRST           0x00080000
#define SHIFT_IMG_SOC_SRST          19
#define REGNUM_IMG_SOC_SRST         0x0004

#define MASK_IMG_SOC_DREQ           0x00100000
#define SHIFT_IMG_SOC_DREQ          20
#define REGNUM_IMG_SOC_DREQ         0x0004

#define MASK_IMG_SOC_LIST_FIN_CTL   0x00400000
#define SHIFT_IMG_SOC_LIST_FIN_CTL  22
#define REGNUM_IMG_SOC_LIST_FIN_CTL 0x0004

#define MASK_IMG_SOC_PI             0x03000000
#define SHIFT_IMG_SOC_PI            24
#define REGNUM_IMG_SOC_PI           0x0004
#define IMG_SOC_PI_1		0x00000002
#define IMG_SOC_PI_2		0x00000001
#define IMG_SOC_PI_4		0x00000000

#define MASK_IMG_SOC_DIR            0x04000000
#define SHIFT_IMG_SOC_DIR           26
#define REGNUM_IMG_SOC_DIR          0x0004

#define MASK_IMG_SOC_PW             0x18000000
#define SHIFT_IMG_SOC_PW            27
#define REGNUM_IMG_SOC_PW           0x0004

#define MASK_IMG_SOC_TRANSFER_IEN   0x20000000
#define SHIFT_IMG_SOC_TRANSFER_IEN  29
#define REGNUM_IMG_SOC_TRANSFER_IEN 0x0004

#define MASK_IMG_SOC_BSWAP          0x40000000
#define SHIFT_IMG_SOC_BSWAP         30
#define REGNUM_IMG_SOC_BSWAP        0x0004

#define MASK_IMG_SOC_LIST_IEN       0x80000000
#define SHIFT_IMG_SOC_LIST_IEN      31
#define REGNUM_IMG_SOC_LIST_IEN     0x0004

/* Register DMAC_SETUP */
#define IMG_SOC_DMAC_SETUP(X)       (0x0000 + (32 * (X)))
#define MASK_IMG_SOC_START_ADDRESS  0xFFFFFFF
#define SHIFT_IMG_SOC_START_ADDRESS 0
#define REGNUM_IMG_SOC_START_ADDRESS 0x0000

/* Number of entries in table DMAC */

#define IMG_SOC_DMAC_SIZE_UINT32    31
#define IMG_SOC_DMAC_NUM_ENTRIES    4

/*
	Byte range covering the group DMAC file
*/

#define IMG_SOC_DMAC_REGISTERS_START		0x00000000
#define IMG_SOC_DMAC_REGISTERS_END  		0x00000083

#define MTX_CCBCTRL_ROFF		0
#define MTX_CCBCTRL_COMPLETE		4
#define MTX_CCBCTRL_CCBSIZE		8
#define MTX_CCBCTRL_QP			12
#define MTX_CCBCTRL_FRAMESKIP		20
#define MTX_CCBCTRL_INITQP		24

/* We do not use bitfields as they are not handled
 * efficiently by MTX (we beleive!)
 */
#define OPNUM_MASK		(0xffff0000)
#define OPNUM_SHIFT		(16)
#define CMDSIZE_MASK	(0x0000ff00)
#define CMDSIZE_SHIFT	(8)
#define CMDID_MASK		(0x000000ff)
#define CMDID_SHIFT		(0)

/* **************** mtx register define **************** */
/* XXX: the above register define is the subset of mtx register used
 * by testbench somewhere
 */
#define MTX_CR_MTX_ENABLE           0x0000
#define MASK_MTX_MTX_ENABLE         0x00000001
#define SHIFT_MTX_MTX_ENABLE        0
#define REGNUM_MTX_MTX_ENABLE       0x0000

#define MASK_MTX_MTX_TOFF           0x00000002
#define SHIFT_MTX_MTX_TOFF          1
#define REGNUM_MTX_MTX_TOFF         0x0000

#define MASK_MTX_MTX_TSTOPPED       0x00000004
#define SHIFT_MTX_MTX_TSTOPPED      2
#define REGNUM_MTX_MTX_TSTOPPED     0x0000

#define MASK_MTX_MTX_STEP_REC       0x000000F0
#define SHIFT_MTX_MTX_STEP_REC      4
#define REGNUM_MTX_MTX_STEP_REC     0x0000

#define MASK_MTX_MTX_ARCH           0x00000800
#define SHIFT_MTX_MTX_ARCH          11
#define REGNUM_MTX_MTX_ARCH         0x0000

#define MASK_MTX_MTX_TCAPS          0x0000F000
#define SHIFT_MTX_MTX_TCAPS         12
#define REGNUM_MTX_MTX_TCAPS        0x0000

#define MASK_MTX_MTX_MIN_REV        0x00FF0000
#define SHIFT_MTX_MTX_MIN_REV       16
#define REGNUM_MTX_MTX_MIN_REV      0x0000

#define MASK_MTX_MTX_MAJ_REV        0xFF000000
#define SHIFT_MTX_MTX_MAJ_REV       24
#define REGNUM_MTX_MTX_MAJ_REV      0x0000

/* Register CR_MTX_STATUS */
#define MTX_CR_MTX_STATUS           0x0008
#define MASK_MTX_MTX_CF_C           0x00000001
#define SHIFT_MTX_MTX_CF_C          0
#define REGNUM_MTX_MTX_CF_C         0x0008

#define MASK_MTX_MTX_CR_O           0x00000002
#define SHIFT_MTX_MTX_CR_O          1
#define REGNUM_MTX_MTX_CR_O         0x0008

#define MASK_MTX_MTX_CF_N           0x00000004
#define SHIFT_MTX_MTX_CF_N          2
#define REGNUM_MTX_MTX_CF_N         0x0008

#define MASK_MTX_MTX_CF_Z           0x00000008
#define SHIFT_MTX_MTX_CF_Z          3
#define REGNUM_MTX_MTX_CF_Z         0x0008

#define MASK_MTX_MTX_LSM_STEP       0x00000700
#define SHIFT_MTX_MTX_LSM_STEP      8
#define REGNUM_MTX_MTX_LSM_STEP     0x0008

#define MASK_MTX_MTX_HREASON        0x000C0000
#define SHIFT_MTX_MTX_HREASON       18
#define REGNUM_MTX_MTX_HREASON      0x0008

/* Register CR_MTX_KICK */
#define MTX_CR_MTX_KICK             0x0080
#define MASK_MTX_MTX_KICK           0x0000FFFF
#define SHIFT_MTX_MTX_KICK          0
#define REGNUM_MTX_MTX_KICK         0x0080

/* Register CR_MTX_KICKI */
#define MTX_CR_MTX_KICKI            0x0088
#define MASK_MTX_MTX_KICKI          0x0000FFFF
#define SHIFT_MTX_MTX_KICKI         0
#define REGNUM_MTX_MTX_KICKI        0x0088

/* Register CR_MTX_FAULT0 */
#define MTX_CR_MTX_FAULT0           0x0090
#define MASK_MTX_REQ_SB             0x000000FF
#define SHIFT_MTX_REQ_SB            0
#define REGNUM_MTX_REQ_SB           0x0090

#define MASK_MTX_REQ_RN_W           0x00000100
#define SHIFT_MTX_REQ_RN_W          8
#define REGNUM_MTX_REQ_RN_W         0x0090

#define MASK_MTX_REQ_STATE          0x00000C00
#define SHIFT_MTX_REQ_STATE         10
#define REGNUM_MTX_REQ_STATE        0x0090

#define MASK_MTX_REQ_LD_DEST        0x00FF0000
#define SHIFT_MTX_REQ_LD_DEST       16
#define REGNUM_MTX_REQ_LD_DEST      0x0090

#define MASK_MTX_REQ_LD_REG         0xF8000000
#define SHIFT_MTX_REQ_LD_REG        27
#define REGNUM_MTX_REQ_LD_REG       0x0090

/* Register CR_MTX_REGISTER_READ_WRITE_DATA */
#define MTX_CR_MTX_REGISTER_READ_WRITE_DATA 0x00F8
/* Register CR_MTX_REGISTER_READ_WRITE_REQUEST */
#define MTX_CR_MTX_REGISTER_READ_WRITE_REQUEST 0x00FC
#define MASK_MTX_MTX_USPECIFIER     0x0000000F
#define SHIFT_MTX_MTX_USPECIFIER    0
#define REGNUM_MTX_MTX_USPECIFIER   0x00FC

#define MASK_MTX_MTX_RSPECIFIER     0x00000070
#define SHIFT_MTX_MTX_RSPECIFIER    4
#define REGNUM_MTX_MTX_RSPECIFIER   0x00FC

#define MASK_MTX_MTX_RNW            0x00010000
#define SHIFT_MTX_MTX_RNW           16
#define REGNUM_MTX_MTX_RNW          0x00FC

#define MASK_MTX_MTX_DREADY         0x80000000
#define SHIFT_MTX_MTX_DREADY        31
#define REGNUM_MTX_MTX_DREADY       0x00FC

/* Register CR_MTX_RAM_ACCESS_DATA_EXCHANGE */
#define MTX_CR_MTX_RAM_ACCESS_DATA_EXCHANGE 0x0100
/* Register CR_MTX_RAM_ACCESS_DATA_TRANSFER */
#define MTX_CR_MTX_RAM_ACCESS_DATA_TRANSFER 0x0104
/* Register CR_MTX_RAM_ACCESS_CONTROL */
#define MTX_CR_MTX_RAM_ACCESS_CONTROL 0x0108
#define MASK_MTX_MTX_MCMR           0x00000001
#define SHIFT_MTX_MTX_MCMR          0
#define REGNUM_MTX_MTX_MCMR         0x0108

#define MASK_MTX_MTX_MCMAI          0x00000002
#define SHIFT_MTX_MTX_MCMAI         1
#define REGNUM_MTX_MTX_MCMAI        0x0108

#define MASK_MTX_MTX_MCM_ADDR       0x000FFFFC
#define SHIFT_MTX_MTX_MCM_ADDR      2
#define REGNUM_MTX_MTX_MCM_ADDR     0x0108

#define MASK_MTX_MTX_MCMID          0x0FF00000
#define SHIFT_MTX_MTX_MCMID         20
#define REGNUM_MTX_MTX_MCMID        0x0108

/* Register CR_MTX_RAM_ACCESS_STATUS */
#define MTX_CR_MTX_RAM_ACCESS_STATUS 0x010C
#define MASK_MTX_MTX_MTX_MCM_STAT   0x00000001
#define SHIFT_MTX_MTX_MTX_MCM_STAT  0
#define REGNUM_MTX_MTX_MTX_MCM_STAT 0x010C

/* Register CR_MTX_SOFT_RESET */
#define MTX_CR_MTX_SOFT_RESET       0x0200
#define MASK_MTX_MTX_RESET          0x00000001
#define SHIFT_MTX_MTX_RESET         0
#define REGNUM_MTX_MTX_RESET        0x0200

/* Register CR_MTX_SYSC_CDMAC */
#define MTX_CR_MTX_SYSC_CDMAC       0x0340
#define MASK_MTX_LENGTH             0x0000FFFF
#define SHIFT_MTX_LENGTH            0
#define REGNUM_MTX_LENGTH           0x0340

#define MASK_MTX_ENABLE             0x00010000
#define SHIFT_MTX_ENABLE            16
#define REGNUM_MTX_ENABLE           0x0340

#define MASK_MTX_RNW                0x00020000
#define SHIFT_MTX_RNW               17
#define REGNUM_MTX_RNW              0x0340

#define MASK_MTX_BURSTSIZE          0x07000000
#define SHIFT_MTX_BURSTSIZE         24
#define REGNUM_MTX_BURSTSIZE        0x0340

/* Register CR_MTX_SYSC_CDMAA */
#define MTX_CR_MTX_SYSC_CDMAA       0x0344
#define MASK_MTX_CDMAA_ADDRESS      0x03FFFFFC
#define SHIFT_MTX_CDMAA_ADDRESS     2
#define REGNUM_MTX_CDMAA_ADDRESS    0x0344

/* Register CR_MTX_SYSC_CDMAS0 */
#define MTX_CR_MTX_SYSC_CDMAS0      0x0348
#define MASK_MTX_DONOTHING          0x00000001
#define SHIFT_MTX_DONOTHING         0
#define REGNUM_MTX_DONOTHING        0x0348

#define MASK_MTX_DMAREQUEST         0x00000010
#define SHIFT_MTX_DMAREQUEST        4
#define REGNUM_MTX_DMAREQUEST       0x0348

#define MASK_MTX_RAMNUMBER          0x00000F00
#define SHIFT_MTX_RAMNUMBER         8
#define REGNUM_MTX_RAMNUMBER        0x0348

#define MASK_MTX_COUNT              0xFFFF0000
#define SHIFT_MTX_COUNT             16
#define REGNUM_MTX_COUNT            0x0348

/* Register CR_MTX_SYSC_CDMAS1 */
#define MTX_CR_MTX_SYSC_CDMAS1      0x034C
#define MASK_MTX_CDMAS1_ADDRESS     0x03FFFFFC
#define SHIFT_MTX_CDMAS1_ADDRESS    2
#define REGNUM_MTX_CDMAS1_ADDRESS   0x034C

/* Register CR_MTX_SYSC_CDMAT */
#define MTX_CR_MTX_SYSC_CDMAT       0x0350
#define MASK_MTX_TRANSFERDATA       0xFFFFFFFF
#define SHIFT_MTX_TRANSFERDATA      0
#define REGNUM_MTX_TRANSFERDATA     0x0350

/* **************** DMAC define **************** */
enum  DMAC_eBSwap {
	DMAC_BSWAP_NO_SWAP = 0x0,/* !< No byte swapping will be performed. */
	DMAC_BSWAP_REVERSE = 0x1,/* !< Byte order will be reversed. */
};

enum DMAC_ePW {
	DMAC_PWIDTH_32_BIT = 0x0,/* !< Peripheral width 32-bit. */
	DMAC_PWIDTH_16_BIT = 0x1,/* !< Peripheral width 16-bit. */
	DMAC_PWIDTH_8_BIT = 0x2,/* !< Peripheral width 8-bit. */
};

enum DMAC_eAccDel {
	DMAC_ACC_DEL_0 = 0x0,	/* !< Access delay zero clock cycles */
	DMAC_ACC_DEL_256 = 0x1,	/* !< Access delay 256 clock cycles */
	DMAC_ACC_DEL_512 = 0x2,	/* !< Access delay 512 clock cycles */
	DMAC_ACC_DEL_768 = 0x3,	/* !< Access delay 768 clock cycles */
	DMAC_ACC_DEL_1024 = 0x4,/* !< Access delay 1024 clock cycles */
	DMAC_ACC_DEL_1280 = 0x5,/* !< Access delay 1280 clock cycles */
	DMAC_ACC_DEL_1536 = 0x6,/* !< Access delay 1536 clock cycles */
	DMAC_ACC_DEL_1792 = 0x7,/* !< Access delay 1792 clock cycles */
};

enum  DMAC_eBurst {
	DMAC_BURST_0 = 0x0,	/* !< burst size of 0 */
	DMAC_BURST_1 = 0x1,	/* !< burst size of 1 */
	DMAC_BURST_2 = 0x2,	/* !< burst size of 2 */
	DMAC_BURST_3 = 0x3,	/* !< burst size of 3 */
	DMAC_BURST_4 = 0x4,	/* !< burst size of 4 */
	DMAC_BURST_5 = 0x5,	/* !< burst size of 5 */
	DMAC_BURST_6 = 0x6,     /* !< burst size of 6 */
	DMAC_BURST_7 = 0x7,	/* !< burst size of 7 */
};

#define DMAC_VALUE_COUNT(BSWAP, PW, DIR, PERIPH_INCR, COUNT)        \
	((((BSWAP) << SHIFT_IMG_SOC_BSWAP) & MASK_IMG_SOC_BSWAP)|	\
		(((PW) << SHIFT_IMG_SOC_PW) & MASK_IMG_SOC_PW)|		\
		(((DIR) << SHIFT_IMG_SOC_DIR) & MASK_IMG_SOC_DIR)|	\
		(((PERIPH_INCR) << SHIFT_IMG_SOC_PI) & MASK_IMG_SOC_PI)| \
		(((COUNT) << SHIFT_IMG_SOC_CNT) & MASK_IMG_SOC_CNT))

#define DMAC_VALUE_PERIPH_PARAM(ACC_DEL, INCR, BURST)             \
((((ACC_DEL) << SHIFT_IMG_SOC_ACC_DEL) & MASK_IMG_SOC_ACC_DEL)|	\
(((INCR) << SHIFT_IMG_SOC_INCR) & MASK_IMG_SOC_INCR)|             \
(((BURST) << SHIFT_IMG_SOC_BURST) & MASK_IMG_SOC_BURST))


#ifdef DEBUG_FUNCTION

void dump_reg(struct drm_psb_private *dev_priv);
void topaz_mmu_test(struct drm_device *dev);

#define DUMP_REG(dev_priv) dump_reg(dev_priv)

#else
#define DUMP_REG(dev_priv)
#endif


/* commands for topaz,shared with user space driver */
enum drm_lnc_topaz_cmd {
	MTX_CMDID_NULL = 0,
	MTX_CMDID_DO_HEADER = 1,
	MTX_CMDID_ENCODE_SLICE = 2,
	MTX_CMDID_WRITEREG = 3,
	MTX_CMDID_START_PIC = 4,
	MTX_CMDID_END_PIC = 5,
	MTX_CMDID_SYNC = 6,
	MTX_CMDID_ENCODE_ONE_ROW = 7,
	MTX_CMDID_FLUSH = 8,
	MTX_CMDID_SW_LEAVE_LOWPOWER = 0xfc,
	MTX_CMDID_SW_ENTER_LOWPOWER = 0xfe,
	MTX_CMDID_SW_NEW_CODEC = 0xff
};

/* codecs topaz supports,shared with user space driver */
enum drm_lnc_topaz_codec {
	IMG_CODEC_JPEG = 0,
	IMG_CODEC_H264_NO_RC,
	IMG_CODEC_H264_VBR,
	IMG_CODEC_H264_CBR,
	IMG_CODEC_H263_NO_RC,
	IMG_CODEC_H263_VBR,
	IMG_CODEC_H263_CBR,
	IMG_CODEC_MPEG4_NO_RC,
	IMG_CODEC_MPEG4_VBR,
	IMG_CODEC_MPEG4_CBR,
	IMG_CODEC_NUM
};

/* XXX: it's a copy of msvdx cmd queue. should have some change? */
struct lnc_topaz_cmd_queue {
	struct list_head head;
	void *cmd;
	unsigned long cmd_size;
	uint32_t sequence;
};


struct topaz_cmd_header {
	union {
		struct {
			unsigned long id:8;
			unsigned long size:8;
			unsigned long seq:16;
		};
		uint32_t val;
	};
};

/* external function declare */
/* lnc_topazinit.c */
int lnc_topaz_init(struct drm_device *dev);
int lnc_topaz_uninit(struct drm_device *dev);
int lnc_topaz_reset(struct drm_psb_private *dev_priv);
int topaz_init_fw(struct drm_device *dev);
int topaz_setup_fw(struct drm_device *dev, enum drm_lnc_topaz_codec codec);
int topaz_wait_for_register(struct drm_psb_private *dev_priv,
			    uint32_t addr, uint32_t value,
			    uint32_t enable);
void topaz_write_mtx_mem(struct drm_psb_private *dev_priv,
			 uint32_t byte_addr, uint32_t val);
uint32_t topaz_read_mtx_mem(struct drm_psb_private *dev_priv,
			    uint32_t byte_addr);
void topaz_write_mtx_mem_multiple_setup(struct drm_psb_private *dev_priv,
					uint32_t addr);
void topaz_write_mtx_mem_multiple(struct drm_psb_private *dev_priv,
				  uint32_t val);

/* lnc_topaz.c */
void lnc_topaz_interrupt(struct drm_device *dev, uint32_t topaz_stat);

int lnc_cmdbuf_video(struct drm_file *priv,
		struct list_head *validate_list,
		uint32_t fence_type,
		struct drm_psb_cmdbuf_arg *arg,
		struct ttm_buffer_object *cmd_buffer,
		struct psb_ttm_fence_rep *fence_arg);

void lnc_topaz_flush_cmd_queue(struct drm_device *dev);
void lnc_topaz_lockup(struct drm_psb_private *dev_priv, int *topaz_lockup,
		      int *topaz_idle);
void topaz_mtx_kick(struct drm_psb_private *dev_priv, uint32_t kick_cout);

uint32_t psb_get_default_pd_addr(struct psb_mmu_driver *driver);

/* macros to get/set CCB control data */
#define WB_CCB_CTRL_RINDEX(dev_priv) (*((uint32_t *)dev_priv->topaz_ccb_wb))
#define WB_CCB_CTRL_SEQ(dev_priv) (*((uint32_t *)dev_priv->topaz_ccb_wb+1))

#define POLL_WB_RINDEX(dev_priv,value)				\
do {								\
	int i;							\
	for (i = 0; i < 10000; i++) {				\
		if (WB_CCB_CTRL_RINDEX(dev_priv) == value)	\
			break;					\
		else						\
			DRM_UDELAY(100);			\
	}							\
	if (WB_CCB_CTRL_RINDEX(dev_priv) != value) {		\
		DRM_ERROR("TOPAZ: poll rindex timeout\n");	\
		ret = -EBUSY;					\
	}							\
} while (0)

#define CCB_CTRL_RINDEX(dev_priv)			\
	topaz_read_mtx_mem(dev_priv,			\
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_ROFF)

#define CCB_CTRL_RINDEX(dev_priv)			\
	topaz_read_mtx_mem(dev_priv,			\
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_ROFF)

#define CCB_CTRL_QP(dev_priv)						\
	topaz_read_mtx_mem(dev_priv,					\
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_QP)

#define CCB_CTRL_SEQ(dev_priv)						\
	topaz_read_mtx_mem(dev_priv,					\
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_COMPLETE)

#define CCB_CTRL_FRAMESKIP(dev_priv)				   \
	topaz_read_mtx_mem(dev_priv,				   \
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_FRAMESKIP)

#define CCB_CTRL_SET_QP(dev_priv, qp)					\
	topaz_write_mtx_mem(dev_priv,					\
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_QP, qp)

#define CCB_CTRL_SET_INITIALQP(dev_priv, qp)			    \
	topaz_write_mtx_mem(dev_priv,				    \
			dev_priv->topaz_ccb_ctrl_addr + MTX_CCBCTRL_INITQP, qp)


#define TOPAZ_BEGIN_CCB(dev_priv)					\
	topaz_write_mtx_mem_multiple_setup(dev_priv,			\
					dev_priv->topaz_ccb_buffer_addr + \
					dev_priv->topaz_cmd_windex * 4)

#define TOPAZ_OUT_CCB(dev_priv, cmd)					\
do {									\
	topaz_write_mtx_mem_multiple(dev_priv, cmd);			\
	dev_priv->topaz_cmd_windex++;					\
} while (0)

#define TOPAZ_END_CCB(dev_priv,kick_count)	\
	topaz_mtx_kick(dev_priv, 1);

static inline char *cmd_to_string(int cmd_id)
{
	switch (cmd_id) {
	case MTX_CMDID_START_PIC:
		return "MTX_CMDID_START_PIC";
	case MTX_CMDID_END_PIC:
		return "MTX_CMDID_END_PIC";
	case MTX_CMDID_DO_HEADER:
		return "MTX_CMDID_DO_HEADER";
	case MTX_CMDID_ENCODE_SLICE:
		return "MTX_CMDID_ENCODE_SLICE";
	case MTX_CMDID_SYNC:
		return "MTX_CMDID_SYNC";

	default:
		return "Undefined command";

	}
}

static inline char *codec_to_string(int codec)
{
	switch (codec) {
	case IMG_CODEC_H264_NO_RC:
		return "H264_NO_RC";
	case IMG_CODEC_H264_VBR:
		return "H264_VBR";
	case IMG_CODEC_H264_CBR:
		return "H264_CBR";
	case IMG_CODEC_H263_NO_RC:
		return "H263_NO_RC";
	case IMG_CODEC_H263_VBR:
		return "H263_VBR";
	case IMG_CODEC_H263_CBR:
		return "H263_CBR";
	case IMG_CODEC_MPEG4_NO_RC:
		return "MPEG4_NO_RC";
	case IMG_CODEC_MPEG4_VBR:
		return "MPEG4_VBR";
	case IMG_CODEC_MPEG4_CBR:
		return "MPEG4_CBR";
	default:
		return "Undefined codec";
	}
}

static inline void lnc_topaz_enableirq(struct drm_device *dev)
{
	struct drm_psb_private *dev_priv = dev->dev_private;
	uint32_t ier = dev_priv->vdc_irq_mask | _LNC_IRQ_TOPAZ_FLAG;

	PSB_DEBUG_IRQ("TOPAZ: enable IRQ\n");

	TOPAZ_WRITE32(TOPAZ_CR_IMG_TOPAZ_INTENAB,
		F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_MAS_INTEN) |
		/* F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTEN_MVEA) | */
		F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTEN_MMU_FAULT) |
		F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTEN_MTX) |
		F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTEN_MTX_HALT));

	PSB_WVDC32(ier, PSB_INT_ENABLE_R); /* essential */
}

static inline void lnc_topaz_disableirq(struct drm_device *dev)
{

	struct drm_psb_private *dev_priv = dev->dev_private;
	uint32_t ier = dev_priv->vdc_irq_mask & (~_LNC_IRQ_TOPAZ_FLAG);

	PSB_DEBUG_INIT("TOPAZ: disable IRQ\n");

	TOPAZ_WRITE32(TOPAZ_CR_IMG_TOPAZ_INTENAB, 0);
	PSB_WVDC32(ier, PSB_INT_ENABLE_R); /* essential */
}

static inline void lnc_topaz_clearirq(struct drm_device *dev,
				uint32_t clear_topaz)
{
	struct drm_psb_private *dev_priv = dev->dev_private;

	PSB_DEBUG_INIT("TOPAZ: clear IRQ\n");
	if (clear_topaz != 0)
		TOPAZ_WRITE32(TOPAZ_CR_IMG_TOPAZ_INTCLEAR, clear_topaz);

	PSB_WVDC32(_LNC_IRQ_TOPAZ_FLAG, PSB_INT_IDENTITY_R);
}

static inline uint32_t lnc_topaz_queryirq(struct drm_device *dev)
{
	struct drm_psb_private *dev_priv = dev->dev_private;
	uint32_t val, iir, clear = 0;

	TOPAZ_READ32(TOPAZ_CR_IMG_TOPAZ_INTSTAT, &val);
	iir = PSB_RVDC32(PSB_INT_IDENTITY_R);

	if ((val == 0) && (iir == 0)) {/* no interrupt */
		PSB_DEBUG_GENERAL("TOPAZ: no interrupt,IIR=TOPAZ_INTSTAT=0\n");
		return 0;
	}

	PSB_DEBUG_IRQ("TOPAZ:TOPAZ_INTSTAT=0x%08x,IIR=0%08x\n", val, iir);

	if (val & (1<<31))
		PSB_DEBUG_IRQ("TOPAZ:interrupt pin activated,seq=0x%08x,"
			"sync_seq=0x%08x\n", CCB_CTRL_SEQ(dev_priv),
			*(uint32_t *)dev_priv->topaz_sync_addr);
	else
		PSB_DEBUG_IRQ("TOPAZ:interrupt pin not activated,seq=0x%08x,"
			"sync_seq=0x%08x\n", CCB_CTRL_SEQ(dev_priv),
			*(uint32_t *)dev_priv->topaz_sync_addr);

	if (val & 0x8) {
		uint32_t mmu_status, mmu_req;

		TOPAZ_READ32(TOPAZ_CR_MMU_STATUS, &mmu_status);
		TOPAZ_READ32(TOPAZ_CR_MMU_MEM_REQ, &mmu_req);

		PSB_DEBUG_IRQ("TOPAZ: detect a page fault interrupt, "
			"address=0x%08x,mem req=0x%08x\n",
			mmu_status, mmu_req);
		clear |= F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTCLR_MMU_FAULT);
	}

	if (val & 0x4) {
		PSB_DEBUG_IRQ("TOPAZ: detect a MTX_HALT interrupt\n");
		clear |= F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX_HALT);
	}

	if (val & 0x2) {
		PSB_DEBUG_IRQ("TOPAZ: detect a MTX interrupt\n");
		clear |= F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTCLR_MTX);

	}

	if (val & 0x1) {
		PSB_DEBUG_IRQ("TOPAZ: detect a MVEA interrupt\n");
		clear |= F_ENCODE(1, TOPAZ_CR_IMG_TOPAZ_INTCLR_MVEA);
	}

	return clear;
}

#endif	/* _LNC_TOPAZ_H_ */
