#
# Copyright (c) 2005-2006 Hewlett-Packard Development Company, L.P.
# Contributed by Stephane Eranian <eranian@gmail.com>
#
obj-y =	perfmon_ctx.o perfmon_file.o      \
	perfmon_attach.o perfmon_res.o    \
	perfmon_init.o perfmon_activate.o \
	perfmon_intr.o perfmon_rw.o	  \
	perfmon_ctxsw.o perfmon_pmu.o	  \
	perfmon_syscalls.o perfmon_sysfs.o
