#
# Copyright (c) 2005-2007 Hewlett-Packard Development Company, L.P.
# Contributed by Stephane Eranian <eranian@hpl.hp.com>
#
obj-$(CONFIG_PERFMON)			+= perfmon.o
obj-$(CONFIG_X86_PERFMON_INTEL_ARCH)	+= perfmon_intel_arch.o
obj-$(CONFIG_X86_PERFMON_AMD64)		+= perfmon_amd64.o
