/* File autogenerated */

#ifndef __UWB_BUGS_H__
#define __UWB_BUGS_H__

#include <linux/uwb/bugs-macros.h>

#define UWB_BUG_45 1
#define UWB_BUG_78 0
#define UWB_BUG_238 1
#define UWB_BUG_292 0
#define UWB_BUG_293 1
#define UWB_BUG_371 1
#define UWB_BUG_374 0
#define UWB_BUG_384 0
#define UWB_BUG_415 1
#define UWB_BUG_418 1
#define UWB_BUG_445 1
#define UWB_BUG_456 1
#define UWB_BUG_457 1
#define UWB_BUG_458 1
#define UWB_BUG_459 1
#define UWB_BUG_461 1
#define UWB_BUG_462 0
#define UWB_BUG_464 1
#define UWB_BUG_469 1
#define UWB_BUG_479 1
#define UWB_BUG_487 1
#define UWB_BUG_501 1
#define UWB_BUG_513 1
#define UWB_BUG_514 1
#define UWB_BUG_543 1
#define UWB_BUG_548 1
#define UWB_BUG_573 0
#define UWB_BUG_010612024004 1

#define UWB_BUGS_ENABLED " 45 238 293 371 415 418 445 456 457 458 459 461 464 469 479 487 501 513 514 543 548 010612024004"

enum { UWB_BUG_COUNT = 28 };

#endif /* #ifndef __UWB_BUGS_H__ */
