/* File autogenerated */
/* @lket@ignore-file */
#define NEED_BITMAP_COPY_LE
#define NEED_USB_DEV_RESET_DELAYED
#undef CONFIG_USB_WUSB
#undef CONFIG_USB_HWA_HCD
#define CONFIG_UWB 1
#define CONFIG_UWB_HWA 1
#define CONFIG_UWB_WHCI 1
#define CONFIG_UWB_WLP 1
#define CONFIG_UWB_I1480U 1
#define CONFIG_UWB_I1480U_WLP 1
